### ISSUE TITLE
More documentation of the XML files

### ISSUE THREAD

**Issue by dereulenspiegel** [Homegear/Homegear#1]
Hello,

I am currently developing a java library to talk to the Homematic LAN configuration device. While researching the BidCos protocol I found your wiki on homegear.eu. It is a really great start to get some insight into the protocol. I get the feeling that you are able to understand the device specific payloads with the help of the XML files used by the Homematic software. Could you document this process a little bit more? I saw that there are frame elements in the XML. These seem to describe the actual positions of the bytes in the frame. But what does for example an index of 9 or 10 mean? Is this 9th or 10th byte in the payload or in the whole packet? If it is the position in the whole packet I must have understand the packet format wrong, since I thought that the payload starts at byte 10?
Also what can I do with the channel and paramset elements. If you have more information on these elements could you add some explanation?
For example is it possible to read the device specific parts of the pairing process from these elements?

Thanks in advance for your help

**Comment by hfedcba** [comment]
I'm closing this issue for now. Documentation will come ;-).
