### ISSUE TITLE
systemd service

### ISSUE THREAD

**Issue by jcw9930** [Homegear/Homegear#120]
For homegear to run successfully under systemd supervision a few things seem to be necessary:

- create the socket also in non daemon mode (systemd prefers non-forking services)
- create the lock file in a place where the user homegear can write to (is the lock file really necessary?)
- currently homegear immediately exits when running as systemd unit

Here is a simple attempt:

[root@raspberry ~]# cat /etc/systemd/system/homegear.service
[Unit]
Description=Homegear daemon

[Service]
User=homegear
Group=homegear
ExecStart=/usr/local/bin/homegear

[Install]
WantedBy=multi-user.target

**Comment by promille** [comment]
Same probleme here. 

`Module HomeMatic BidCoS: CUL "My-CUL": Couldn't create lockfile /var/lock/ttyACM0.lock: Permission denied`

**Comment by hfedcba** [comment]
Did you maybe create the lock file as root? Delete the lock file manually and restart Homegear. Does that work?

**Comment by promille** [comment]
No the homegear user does not have permissions to /var/lock by default. So the creation of the lock file will fail. I have changed the lock file path and the bidcos module is running now.

I am struggeling with the patch apply. I have changed the path manually.

`--- a/src/homegear-homematicbidcos/src/PhysicalInterfaces/Cul.cpp   2016-10-18 20:33:38.896969711 +0200
+++ b/src/homegear-homematicbidcos/src/PhysicalInterfaces/Cul.cpp   2016-10-14 13:08:47.000000000 +0200
@@ -149,7 +149,7 @@
    {
        if(_fileDescriptor->descriptor > -1) closeDevice();

-       _lockfile = "/var/run/homegear" + _settings->device.substr(_settings->device.find_last_of('/')) + ".lock";
+       _lockfile = "/var/lock" + _settings->device.substr(_settings->device.find_last_of('/')) + ".lock";
        int lockfileDescriptor = open(_lockfile.c_str(), O_WRONLY | O_EXCL | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH);
        if(lockfileDescriptor == -1)
        {`

**Comment by jcw9930** [comment]
that'd be really great to have upstream

2016-10-18 21:18 GMT+02:00 promille <notifications@github.com>:

**Comment by hfedcba** [comment]
Hmm, I don't think, "/var/run" is the right directory to place lock files: https://www.debian.org/doc/packaging-manuals/fhs/fhs-2.3.html#VARLOCKLOCKFILES

According to the Debian documentation "/var/lock" is the correct location. I just realized, the naming is not correct though...

By default "/var/lock" is writeable for users. Any idea why it might not be on your system?

**Comment by promille** [comment]
I am using Arch Linux. And yes /var/lock seems to be writeable but there's a symlink to /var/run/lock and this path isn't.

> [root@ARCH log]# ls -la /var/lock
lrwxrwxrwx 1 root root 11 Sep 30  2015 /var/lock -> ../run/lock
[root@ARCH log]# ls -la /var/run/lock
total 0
drwxr-xr-x  3 root root  60 Oct 18 18:10 .
drwxr-xr-x 24 root root 700 Oct 18 18:18 ..
drwxr-xr-x  2 root root  40 Oct 18 18:10 subsys

This is the default setup. I have not changed anything or created this symlink

**Comment by jcw9930** [comment]
on fedora /var/lock is also a symlink to /var/run/lock. looks exactly the
same

2016-10-18 21:43 GMT+02:00 promille <notifications@github.com>:

**Comment by hfedcba** [comment]
Ok, I will make the lock file path configurable.

**Comment by hfedcba** [comment]
Done 😃.

**Comment by promille** [comment]
wow that was fast!
I have seen your ccc presentation on youtube ... great work ;)
First HomeMatic Switch is toggling!!!

**Comment by hfedcba** [comment]
Thanks ;-)
