### ISSUE TITLE
Lost Devices in Homematic configurator

### ISSUE THREAD

**Issue by nufer** [Homegear/Homegear#171]
if I start the HomeMatic Configurator, no devices are listed
![image](https://cloud.githubusercontent.com/assets/6253591/5916375/bf6d81b4-a610-11e4-8452-5981b006de69.png)
the homegear console shows all devices:
![image](https://cloud.githubusercontent.com/assets/6253591/5916392/f4b43cc8-a610-11e4-8dc6-61d6b4423807.png)

**Comment by hfedcba** [comment]
Hey :-),

do you get any kind of error message? Which version of the HomeMatic configurator and of Homegear do you use?

**Comment by nufer** [comment]
I did not get any message, just the empty list.
The configurator has the version 1.517
and, homegear 0.5.24

perhaps, this indicats something:
![image](https://cloud.githubusercontent.com/assets/6253591/5918749/614d3b76-a62c-11e4-852d-cc31d7cd5433.png)

All "direkte geräteverknüpfungen" are present, but the one i marked has an unknown device.

i wanted to try the node.js configurator to compare, but i can't get it running (node.js on your raspberry image does not what i want it to and i have no idea of node.js... ;))

Thanks for your great work!

**Comment by hfedcba** [comment]
Hmm, yes that indicates something. Could you check, if there are any errors in "/var/log/homegear/homegear.err"? Then create a new file "/var/lib/homegear/scripts/Info.php" with the following content:

```php
#!/usr/bin/env php
<?php
include_once("Connect.php");

print_r($Client->send("getDeviceDescription", array("JEQ0557030")));
print_r($Client->send("getAllMetadata", array("JEQ0557030")));
print_r($Client->send("getDeviceDescription", array("JEQ0553131")));
print_r($Client->send("getAllMetadata", array("JEQ0553131")));
?>
```

And send me the output. Hopefully that helps in identifying the error...

In order to get node.js to work, you need to compile it from source ("apt-get install" installs an old version).

Short instruction (as root):

```bash
dpkg --purge nodejs npm
wget http://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz
tar -zxf node-v0.10.36.tar.gz
cd node-v0.10.36
./configure
make
make install
```

**Comment by nufer** [comment]
in the error.log, i see nothing particular:
```
01/27/15 16:21:53.982 Warning: Connection to client number 2165 closed (3).
01/27/15 16:21:54.041 Warning: Connection to client number 2166 closed (3).
01/27/15 16:21:54.098 Warning: Connection to client number 2167 closed (3).
01/27/15 16:21:54.099 Removing server "Homegear". Server has to send "init" again.
```

````
Array
(
    [ADDRESS] => JEQ0557030
    [CHANNELS] => Array
        (
            [0] => 0
            [1] => 1
        )

    [CHILDREN] => Array
        (
            [0] => JEQ0557030:0
            [1] => JEQ0557030:1
        )

    [FAMILY] => 0
    [FIRMWARE] => 2.0
    [FLAGS] => 1
    [ID] => 30
    [INTERFACE] => VBC8084486
    [PARAMSETS] => Array
        (
            [0] => MASTER
        )

    [PARENT] =>
    [PHYSICAL_ADDRESS] => 1941242
    [RF_ADDRESS] => 1941242
    [ROAMING] => 0
    [RX_MODE] => 12
    [TYPE] => HM-CC-VD
    [VERSION] => 8
)
Array
(
    [NAME] => Rad Monia
)
Array
(
    [ADDRESS] => JEQ0553131
    [CHANNELS] => Array
        (
            [0] => 0
            [1] => 1
            [2] => 2
            [3] => 3
        )

    [CHILDREN] => Array
        (
            [0] => JEQ0553131:0
            [1] => JEQ0553131:1
            [2] => JEQ0553131:2
            [3] => JEQ0553131:3
        )

    [FAMILY] => 0
    [FIRMWARE] => 2.1
    [FLAGS] => 1
    [ID] => 14
    [INTERFACE] => VBC8084486
    [PARAMSETS] => Array
        (
            [0] => MASTER
        )

    [PARENT] =>
    [PHYSICAL_ADDRESS] => 1939128
    [RF_ADDRESS] => 1939128
    [ROAMING] => 0
    [RX_MODE] => 12
    [TYPE] => HM-CC-TC
    [VERSION] => 15
)
Array
(
    [NAME] => WT Monia
)
````

**Comment by hfedcba** [comment]
Hmm, looks alright. Could you send me your "/var/lib/homegear/db.sql" to my email address (sathya@laufers.net)? That hopefully lets me reproduce the error...

**Comment by hfedcba** [comment]
As we are trying to move away from the HomeMatic Configurator, I'm closing this issue. It might be fixed.
