### ISSUE TITLE
Add php5 & php5-xmlrpc as a dependency

### ISSUE THREAD

**Issue by vrob01** [Homegear/Homegear#180]
Summary: Installing Homegear via apt-get does not install php5 and php5-xmlrpc
System: Raspberry Pi B+ running up-to-date Raspbian Wheezy with homegear repository

When installing Homegear via the apt-get command presented in the wiki [1], user scripts wont work until the php5 and php5-xmlrpc packages are manually installed by the user.

Expected behaviour:
 - After following the installation procedure outlined in the official documentation, the sample scripts in said document should work

Steps to reproduce:
 1) Remove any existing instances of php / homegear
 2) Install homegear via apt-get:
    `$ apt-get install homegear`
 3) Try to run Test.php in a bash shell as proposed in the wiki [2]:

    $  /var/lib/homegear/scripts/Test.php
    /usr/bin/env: php: No such file or directory

 4) Install php5 meta package
     `$ apt-get install php5`
 5) Try to run Test.php again

    $  /var/lib/homegear/scripts/Test.php
    PHP Fatal error:  Call to undefined function XMLRPC\xmlrpc_encode_request() in /var/lib/homegear/scripts/HM-XMLRPC-Client/Client.php on line 227

 6) Install php5-xmlrpc
 7) Test.php works

Possible solutions:
 - Add php5 & php5-xmlrpc as hard dependencies
 - Since running scripts might not be needed by every user and to maintain a small footprint, pointing out these indirect dependencies in the wiki might suffice

[1] https://www.homegear.eu/index.php/Downloads#Raspbian
[2] https://www.homegear.eu/index.php/First_Steps#Scripting_with_Homegear

**Comment by hfedcba** [comment]
Hey,

you're right, that should've been pointed out. This doesn't matter anymore though, as in version 0.6 of Homegear we switched to "real" PHP as script engine. Because of that PHP becomes a hard dependency.

Cheers,

Sathya
