### ISSUE TITLE
Missing device XML for MAX! Shutter Contact

### ISSUE THREAD

**Issue by vrob01** [Homegear/Homegear#181]
Summary: Homegear is missing a XML spec for the Max! Shutter Contact with device type 0x0400 and firmware 0x0010
System: Raspberry Pi B+ with up-to-date Raspbian Wheezy. Homegear Version is 0.5.24

Expected behaviour:
 - Pairing the MAX! Shutter Contact works and the devices appears in the peer list

Steps to reproduce:
 - Set pairing mode to on in Homegear CLI
 - Start pairing on the shutter contact
 - The logfile presents the following errors:

> 03/08/15 20:00:55.219 MAX packet received (CUL, RSSI: 0x27): 170104001082A7000000001004004C4B4630303239313434
>03/08/15 20:00:55.224 Module MAX: Warning: Device type 0x0400 with firmware version 0x0010 not supported. Sender address 0x1082A7.

 - Device does neither pair nor appear in the peer list

Possible fixes:
 - Copy contents of BC-SC-Rd-WM.xml
 - Set "type_id" to "0x400" and "firmware" to "0x0010"
 - Try to pair the devices
 - Corresponding logfile entries:

>03/08/15 20:06:35.562 MAX packet received (CUL, RSSI: 0x2E): 170204001082A7000000001004004C4B4630303239313434
>03/08/15 20:06:35.808 Module MAX: CUL "CUL": Info: Sending (CUL, WOR: no): 0B320001FD0AB61082A70000
>03/08/15 20:06:35.877 MAX packet received (CUL, RSSI: 0x2A): 0C3202021082A7FD0AB6000112
>03/08/15 20:06:35.891 Info: Can't execute command (Error-no.: 1): no such savepoint: peer49
>03/08/15 20:06:35.916 Module MAX: Added peer 0x1082A7.

 - Device appears in Homegear, not sure about the importance of the error ("Can't execute...")

I will investigate further if the shutter contact works properly.

**Comment by vrob01** [comment]
Update: Using the "addLink"-Method to pair the shutter contact with a wall thermostate and valve drives works as expected. Opening the window will make these devices switch to WINDOW_OPEN_TEMPERATURE.
The log correctly reports the STATE changes.

**Comment by hfedcba** [comment]
Hey,

thanks! The fix will be in the next version.

Cheers,

Sathya
