### ISSUE TITLE
Missing device XML for MAX! Eco Switch

### ISSUE THREAD

**Issue by vrob01** [Homegear/Homegear#182]
For a more complete report, see #181.

Homegear is missing an XML description for the MAX! Eco Switch with type_id = "0x0500" and firmware version = "0x0010".
Copy'n'paste-ing the contents of "BC-PB-2-WM.xml" and adapting the aforementioned properties seems to work. The device will be paired and homegear will report button presses correctly in the log.

**Comment by hfedcba** [comment]
Thanks again ;-). The new XML file will be included in the next version.

Cheers,

Sathya
