### ISSUE TITLE
Using addLink on an Eco Switch causes Homegear to crash

### ISSUE THREAD

**Issue by vrob01** [Homegear/Homegear#183]
Summary: Using `addLink` to pair a MAX! Eco Switch with either a Wall Thermostate or a Valve Drive causes Homegear to crash
System: Raspberry Pi B+ with up-to-date Raspbian Wheezy. Homegear Version is 0.5.24.

Might be related to / caused by #182.

Expected behaviour:
 - Using `addLink` to pair an Eco Switch with any other temperature controlling device (Wall Thermostate, Valve Drive) will either result in these emulating the behaviour when learned to a MAX!Cube (e.g. pressing the "Eco"- button will make these devices switch to `ECO_TEMPERATURE`) or an error message after which Homegear continues to function properly.

Steps to reproduce:
 - Pair any temperature control device (eg. Valve Drive, Wall Thermostate)
 - Pair an Eco Switch (see #182)
 - Use a PHP script to call `addLink`:

>#!/usr/bin/env php
><?php
>include_once("Connect.php");
> 
>print_r($Client->send("addLink", array(14, 1, 3, 1)));
>?>

With 14 being the Eco Switches ID and 3 being an temperature control device (in this example a valve drive). Any combination of channels causes the crash. Valve Drives and Wall Thermostates are afflicted alike.

The PHP errors / stacktrace:

>PHP Fatal error:  Uncaught exception 'XMLRPC\XMLRPCException' with message 'Could not open socket. Host: localhost Port: 2001 Error: Connection refused (111)' in /var/lib/homegear/scripts/HM-XMLRPC-Client/Client.php:135
>Stack trace:
>#0 /var/lib/homegear/scripts/HM-XMLRPC-Client/Client.php(165): XMLRPC\Client->connect()
>#1 /var/lib/homegear/scripts/HM-XMLRPC-Client/Client.php(228): XMLRPC\Client->sendRequest('<?xml version="...')
>#2 /var/lib/homegear/scripts/CreateGroup.php(6): XMLRPC\Client->send('addLink', Array)
>#3 {main}
>  thrown in /var/lib/homegear/scripts/HM-XMLRPC-Client/Client.php on line 135

Corresponding homegear.log lines:

>03/08/15 22:36:07.231 RPC Server (Port 2001): Info: Connection from 127.0.0.1:33252 accepted. Client number: 19
>03/08/15 22:36:07.234 RPC Server (Port 2001): Info: Client number 19 is calling RPC method: >addLink Parameters:
>(Integer) 14
>(Integer) 1
>(Integer) 3
>(Integer) 1
>03/08/15 22:36:07.235 Critical: Signal 11 received. Stopping Homegear...

**Comment by hfedcba** [comment]
Hey,

HomeMatic BidCoS had the same issue in addLink some time ago - no idea why I didn't copy the fix over to MAX!. Thanks! It's fixed now.

Currently no direct links between the Eco switch and other devices are supported. If the link is supported by the device, it's only a matter of XML entries though. I will check today or tomorrow, if a direct link between the switch and other devices is possible and if that's the case add the corresponding XML entries.

Cheers,

Sathya

**Comment by hfedcba** [comment]
We just checked: Direct links between the Eco switch and the valve drive are not possible. It's not supported by the device firmware.
