### ISSUE TITLE
Implement RPC functions "ping" and "pong"

### ISSUE THREAD

**Issue by hfedcba** [Homegear/Homegear#192]

**Comment by cdjm** [comment]
As you are already working on 0.7 do you have an ETA when ping/pong will get implemented?
The guys over at iobroker are changing their code to ping/pong and this creates a lot of warnings in the logfiles:

From IoBroker:  
2016-07-16 16:38:40.275  - error: hm-rpc.3 Ping error: Error: XML-RPC fault: : Requested method not found.

From Homegear:
07/16/16 16:38:40.242 RPC Server (Port 2001): Warning: RPC method not found: ping

**Comment by hfedcba** [comment]
It wasn't implemented. But it is now ;-).

**Comment by cdjm** [comment]
Whoa! That was quick!
Thank you very much. :-)
