### ISSUE TITLE
peer nicht gespeichert ohne neustart

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#193]
I know, you already fixed in that area, but maybe there is still something wrong, or I didn't got the fix somehow :)
In ```0.6.0-110``` debian package, I added a virtual device by rpc method.

I know, in earlier versions, the data got written to the db only on a clean shutdown. But the device was usable in Homegear.

But currently I have the following case.
1. I added a virtual device by rpc.
2. Didnt see it in the ```peers``` table (till here could be the same as already known)
3. But the rpc method ```getPeerId(1, "DEV...")``` didn't find it. (here starts some new behavior)
4. clean restart (```shutdown complete``` visible in the log)
5. check db: peer is in the ```peers``` table
6.  rpc method ```getPeerId(1, "DEV...")``` still didn't find it

**Comment by spali** [comment]
going back to 0.5.24-7 works as expected, even the table does not contain the device, Homegear can find it as normal by rpc methods.

**Comment by hfedcba** [comment]
getPeerId had a really stupid mistake ^^... What do you mean by "didn't see it in the peers table"? Do you open the SQLite3 database directly?

**Comment by spali** [comment]
Jep,  but don't worry, just for debugging such special cases.

**Comment by hfedcba** [comment]
ok, the database really still is an issue. New devices need to be saved immediately. Keep track on issue #191. When it is closed, devices are saved directly after creation.

**Comment by spali** [comment]
No problem, I learned and do always a clean restart. I have anyway a script which setup's all devices from scratch. The only problem is for devices where a manual pairing is required :( but that's definitely not on you to fix.
