### ISSUE TITLE
internal script engine enhacement and/or see what you can reuse

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#195]
Already spoken about. Here my current version of my "API".
I can't suggest to get it 1:1 currently, but maybe use as base.
https://github.com/spali/homegear_php_api

**First explainations, ask for more ;)**

Folder Structure (only the most important stuff):
- ```Homegear```: contains the API
- ```Homegear/init.php```: is what I include in all my scripts, it basically provides a global object $homegear which represents the API
- ```Homegear/autoload```: contains all the classes I use.
- ```Homegear/autoload/Homegear.php```: is the main API
- ```Homegear/autoload/HomegearProxy.php```: is the dynamic proxy, which does nothing than connect and forward all method calls to the rpc Method with the same name
- ```Homegear/autoload/Device*```: some class representation of Physical and Virtual Devices, the virtual once have a bit of logic to update itself from external sources. The also contain the logic for set them up iself including update events etc. (example of setup in ```testSetup.php```)
- ```Homegear/VirtualDeviceProgrammHandler.php```: called by virtual device events (mostly a interval event to update the device values from external source)
- ```Homegear/php-cli.sh```: ignore it, I used it to wrap every call of php scripts from events, at least in 0.6 not required anymore
- ```Homegear/cli_lib.php```: some support for parsing the command line arguments which the events passed to the scripts. example in the device setup or also in the ```Runnable```'s I will list later.
- ```testSetup.php```: Script which I call to make my setup virgin or just for initial setup when I want to start from scratch with my clean setup. It setups the devices and also the logic. (only painpoint I have here currently is for devices which requires manual pairing). I stripped it down just for an example how I setup everything.
- ```logic/Runnable.php```: Class used by everyting which should do something based on event, and is not directly a device. Instances of this class represents more or less something like others know as rules from openhab or whatever similar. It represents the logic in pieces called by events.
- ```logic/LockedRunnable.php```: Some more specific implementations example, one that support locking to prevent concurrent runs of the same class.
- ```logic/RunnableHandler.php```: This script is called by the events and loads the specific "Runnable" to do its work.
- ```logic/Calculate*.php```: Specific "Runnables" which calculates something and get called via ```RunnableHandler.php``` by events.
- ```logic/*rest*```: Just some helper classes I use to share code between the "Runnables".

So from just the list, here a quick step for step instruction from the beginning of a virgin Homegear setup:
1. the ```testSetup.php``` cleanup old stuff, searches new devices (no automatic pair-able devices, waits for manual pairing) and adds my virtual devices. Also calls setup method of the device class to setup the device. Setups also the Runnables at the bottom for calculation stuff. (see point 3).
2. the specific devices classes setup's some events. These events will trigger the ```VirtualDeviceProgrammHandler.php``` script which calls the virtual device ```updateValues()``` method. The method updates the device values.
3. the Runnables has a setup method which has created some events for calculation. These events calls the ```RunnableHandler.php``` with the Runnable name as Parameter. The handler call the ```run()``` method of the Runnable to do whatever it should do. (for example update values based on other values).

So my Idea in general is, if you could integrate more or less the init.php part in the internal script engine. This would make the $homegear available globally to all script. Or only the HomegearProxy object which can handle all rpc-methods, because I know, the Homegear class could be to less efficient.
Something I currently don't like in my API is, that I have to always somehow pass the $homegear to almost all classes, so they know how to access the API. Maybe this could be improved when it would be always available globally in a standard way.

Hope this can give you a first idea of the whole scripts and classes. I know it will take some time to understand. And for sure I'm ready to answer questions all the time. We can also do it by mail (just get it from the forum of my user "grandslam") or we can also do some calls. 
I used to keep texts on github in english to allow non german speaking to read it. But for sure we can also talk in german. It would be also easier for me than english :) 

Just let me know what you prefer or if there any questions.

**Comment by hfedcba** [comment]
Implemented as a new proxy class "Homegear".

**Comment by spali** [comment]
@hfedcba  **just to note and as feedback:**
just started to switch the php API to the internal proxy class.
execution times with debug log via ```writeLog``` enabled for some calculation logic:
before: between 500 and 600 ms
after: between 14 and 19 ms :dart: 

tomorrow with the new build where HomegearException is implemented, I will adapt this to and with this the API can almost transparently use the internal proxy class or if not available the external rpc-proxy class.
We getting closer to the first draft which could be made public of the HomegearPHP :dancers:

**Comment by hfedcba** [comment]
Wow, that's really a huge speed gain :smiley:. I'm really looking forward to test the first version of the HomegearPHP class!!!
