### ISSUE TITLE
listener crash when garbage received

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#197]
as you know, I'm currently testing with a gui which connects by smart socket.
During this I accidentally set the gui to send data to the rpc server.
It was some json websocket request. For sure Homegear didn't know what to to with them.
```
04/24/15 08:45:31.645 RPC Server (Port 2001): Error: Uninterpretable packet received. Closing connection. Packet was:
.......
```
Till here no problem.
But I found out, that my scripts which connects to this rpc server stopped to to there job. I still got logs about Bidcos packages but nothing else. And openhab also died because openhab couldn't connect (or at least didn't get any data) from Homegear.
So I think somehow, the rpc server has crashed or stopped responding.

I don't know if I can reproduce this behaviour. Have to do some tests. But maybe you see in the code what could go wrong in such a case. Or maybe you can just send some garbarge data to the socket.

Not high priority, but not nice if someone can kill kill rpc server with just sending garbage. 

used version: 0.6.0-111 debian amd64 package

**Comment by hfedcba** [comment]
I cannot reproduce the issue. The code fragment for the error message above is pretty small and I don't see any issues... Can you remember any more specifics about the packet you sent?

**Comment by spali** [comment]
Sorry for the late answer, I close this issue. I can't reproduce it too currently.
