### ISSUE TITLE
improved support for forking the homegear process with a specific user

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#199]
To run homegear with a different user than root, there are some quirks required to get it running.
You have implemented it in the init script.
i.e. starting homegear first with ```-s user:user```  as root and then also the ulimit problem.

I would suggest to do it the same way most critical daemons do it which requires initially root permissions.
always start homegear as root, but fork a process as a specified user (by command line). Then you can initialize anything required as root, after fork the process as the specified user.

**advantages:**
- init script don't require such hacks 
   - ulimit can be done before forking
   - any permission problem can be handled befor eforking
- no problem anymore to open a low port (i.e. port 80 is currently only possible when running homegear as root).

**Comment by hfedcba** [comment]
Makes absolutely sense and shouldn't be too much work.

**Comment by spali** [comment]
Depending on the solution... i.e. if you keep the thread running as root running, you could implement an automatic restart if the fork dies.
Just minutes ago, I had a segmentation fault and Homegear  got signal 11 and died... don't ask why, but this got me to the idea, that Homegear could restart itself in such a case :)

**Comment by hfedcba** [comment]
Good idea!!! Nevertheless the error needs to be resolved. You should've gotten a core dump in /var/log/homegear. Could you send it to me together with the log files, the homegear binary (/usr/bin/homegear) and the modules (/var/lib/homegear/modules)? Then I can debug the error ;-).

**Comment by spali** [comment]
No core dump :( I suspect this is because I don't use the default init script currently!?
Or could there be another location for the core dump in such a case?

**Comment by hfedcba** [comment]
ok :'(... The core dump should be in the working directory. For the init script that is /var/log/homegear.

**Comment by hfedcba** [comment]
Done ;-)
