### ISSUE TITLE
Device XML: embedded php in run_program

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#201]
allow to execute in the xml embedded php code under run_program, this would allow to create virtual devices including all required logic to be defined in the device xml.
This opens the world to share the devices to anyone without complicated instruction to setup scripts and events.

**Comment by spali** [comment]
include also program for delete a device, this will give the device a chance to cleanup itself and its created events for example.

**Comment by hfedcba** [comment]
Implemented ;-). The cleanup code can be implemented as well, using \Homegear\Homegear::peerExists(peerId) => When the peer is deleted, the script is still running. The check for "peerExists" then returns false. The script can clean up things and return. The only disadvantage: No parameters of the device can be read anymore, but I hope for now it's ok.

Cheers,

Sathya
