### ISSUE TITLE
Enhancement [Internal Script Engine]: php namespace

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#209]
provide the Homegear class in the namespace Homegear.
So the class is globally available as ```\Homegear\Homegear``` 
This would avoids name collisions in custom scripts.
Every "official" class is provides in the same namespace Homegear.
Hope this is possible in the C API for PHP.

**Comment by hfedcba** [comment]
Using a namespace would be possible and easy (it's just a prefix), but I don't know... It seems to be consensus to only not use namespaces for extension classes (MySQLi, ZipArchive, Tidy, ...). That's why i didn't use a namespace?

**Comment by spali** [comment]
In my opinion, they avoid namespaces to provide backward compatibility for such default classes.
Because namespace is a relative new feature of PHP and many still don't know about it.
But many libraries use namespaces.
Also in my opinion, It could make the code looks better and let the developer organize the libraries better.
For easier usage, PHP supports to use aliases, which allows to use classes in namespaces with a short alias defined by the one who uses the code and also allows to just switch the alias to a different namespace to replace a library i.e.
But for me the most important argument is to not "flood" the global namespace, which should be the privilege of the developer. 
I know, just for this simple class it looks first to be a bit to much. But imagine that others will build more code around this.

**Comment by hfedcba** [comment]
ok, then a Homegear namespace it is ;-).
