### ISSUE TITLE
Enhancement: somehow fake device pairing

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#210]
During testing and for quick re-setup of a died Homegear server, it would be helpfully to somehow export devices.
Concrete, currently I have two devices which does not support forced pairing. So they need physical invocation for pairing.
Especially for such devices, It would be great if I could somehow just replace the Homegear instance and re-setup the devices without the need for pairing again. For example for a quick disaster recovery on a clean system.
Don't know what information is required to make the device think Homegear never changed. 
Is is just some kind of key/id?

My wish would be to have a rpc-method like `addDevice()` where I can submit all required data which makes the device thinking nothing changed.
And maybe a procedure to get the required data out of Homegear.

**Comment by hfedcba** [comment]
You can only move the full database around (and of course recover it). Moving single devices only works, when two Homegear instances have the same central address (the central address is what makes the device think nothing has changed). That's not the case normally and you can't just change the address when there are devices already paired to the old address. So you can't simply add a device, which was paired to a Homegear instance to another Homegear instance without resetting it first.

**Comment by spali** [comment]
Ok,  so for my use case where I always start from scratch, It should be possible to initialize the DB with the same central address? Mabe a "reset db with specific" central address would be an option?

**Comment by hfedcba** [comment]
Yes, that's possible. Either you can replace the central address in the database directly or you can delete the central device using Homegear's CLI and then create a new one with the address of your choice.

**Comment by spali** [comment]
O nice,  didn't realize it's possible to manage this devices too :) 
Will try it this evening and also if it works by rpc calls. Because this would make it possible to recreate a fresh Homegear instance with a complete setup by scripts without any interactions for disaster recovery or testing. 
Let you know about the results.

**Comment by hfedcba** [comment]
Recreating the Homegear device by RPC scripts is not possible. As a quick and dirty solution, you could manage to do it through PHP system calls using the Homegear CLI.

**Comment by spali** [comment]
Ok, have to wait till my father will be back from holiday....because I do everything from remote and I guess I killed the HM-CFG-USB stick and trying to restart the server ended in not ping-able :(
But the advantage will be you can fix Issues till then without being bombed with new once by me :)

**Comment by spali** [comment]
Changing central address ist possible now, at least in bidcos config.
I think this issue can be closed.
