### ISSUE TITLE
Bluetooth sensor support

### ISSUE THREAD

**Issue by hfedcba** [Homegear/Homegear#211]
See: https://forum.homegear.eu/viewtopic.php?f=19&t=234

**Comment by chrwick** [comment]
Do you want to use BlueZ for accessing BLE sensors? https://github.com/gbrault/gattclient
Or something like this? https://github.com/bluekitchen/btstack

**Comment by hfedcba** [comment]
Not a priority at the moment, so I will close the issue for now.
