### ISSUE TITLE
probably missing build-dep: libphp5-embed

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#213]
Hi Sathya

Currently working on a build environment to always get the latest version. During this I found, that installing just the build dependencies does not install all build dependencies.
```libphp5-embed``` is missing I think (at least I get an error ```/usr/bin/ld: cannot find -lphp5```). When I install ```libphp5-embed``` it works.
So maybe this should be added in the ```Build-Depends``` in the debian control file.
Do you build it always in a clean installation or is it possible that you inherited it from somewhere by accident?

**Comment by hfedcba** [comment]
Added ;-). There are actually some more dependencies missing, but they should more or less be installed by default...

BTW there is a docker build system: https://registry.hub.docker.com/u/homegear/build/tags/manage/

**Comment by spali** [comment]
oO fast :+1:

**Comment by spali** [comment]
thanks, found the build system already, but wanted to have one which builds from scratch php and homegear from master source without anything additional like the upload stuff you have included. I will give you the scripts when I'm done with it. Maybe you can use it then to modularize the builds a bit more.

**Comment by spali** [comment]
Building the debian package seems to only miss this. But as you already assume, think too there are some dependencies missing for installation (in my case on a jessie docker base image).
If I find some other dependencies I will create an issue for you.

**Comment by hfedcba** [comment]
Thank you!
