### ISSUE TITLE
Feature Request: remote Script execution

### ISSUE THREAD

**Issue by wbuh** [Homegear/Homegear#218]
A nice feature would be to pass the complete script-code as a string from a remote machine using the .NET dll to be executed by the homegear machine.
For security reasons a config-parameter should allow or restrict "remoteScripting" on the homegear machine. In a second step a restriction to specific IPs as remote machines could limit the risc.

At the moment, I see the advantages: as long as some functions (like setInterface) are not implemented in the .NET dll, remotescripting could be used.
Otherwise endusers must copy such scripts to the raspi and assign correct file access before such helper-scripts could be used by a GUI for endusers - I don't know if beginners are able to to that.

(Issue "moved" from https://github.com/Homegear/HomegearLib.NET/issues/2)

**Comment by spali** [comment]
I would suggest to implement this with a variant of runScript. But instead define a file, just provide the whole php script as parameter. This would be usable in all APIs.
Other Aproach would be to make the homegear cmd utility available on different platforms without complicated dependencies. Then the script file can be local (client) and execute it on a remote homegear instance. Currently it's hard to get only the homegear cmd utility installed.

**Comment by hfedcba** [comment]
As this would be a severe security issue, I won't implement it. With Node-BLUE it can still be realized though.
