### ISSUE TITLE
setting the AES key index does not work correctly using multiple physical interfaces

### ISSUE THREAD

**Issue by mannmarkus** [Homegear/Homegear#219]
Apparently setting currentRFKeyIndex on a HM-LAN-CFG is only working correctly if it also has default=true

I get
```
06/16/15 11:34:19.862 Module HomeMatic BidCoS: Error: Can't update AES key of peer 5. Peer's AES key index is larger than the key index defined in physicalinterfaces.conf.
```
when the HM-LAN-CFG is not the default. If I set it to default it works correctly.

Tested this with 0.5.25. Unfortunately I don't have time to dig into the code now, but if the issue is still open some weeks from now I will be happy to help.

**Comment by hfedcba** [comment]
Could you send me your physicalinterfaces.conf (changing the AES keys of course)? Is currentRFKeyIndex the same on both HM-CFG-LAN?
