### ISSUE TITLE
homegear on CentOS 7 using XFS

### ISSUE THREAD

**Issue by telkamp** [Homegear/Homegear#223]
I've just managed to run homegear on a CentOS 7 system using a XFS file system. 
I found out that the code does not run on XFS without modifications.:
The problem is that the function Io::getFiles() in Modules/Base/HelperFunctions uses "d_type" to check if a directory entry is a file (or another directory entry). d_type will always return DT_UNKNOWN on XFS filesystems. The result is, that homegear will not find the modules in /var/lib/homegear/modules/*, and it will not find the device xml files.

My quick & dirty workaround was to check DT_UNKNOWN in Modules/Base/HelperFunctions/Io.cpp#L143:
if((entry->d_type == DT_REG) || (entry->d_type == DT_UNKNOWN))
It would be a better idea to avoid d_type and to use the good old stat() instead. See http://nerdfortress.com/2008/09/19/linux-xfs-does-not-support-direntd_type/

But after that modification and a manual installation, homegear also works on CentOS7 using XFS :-)

**Comment by hfedcba** [comment]
Hey, thanks for finding this issue!

"simply a buggy app", hmmm. Definitely needs to be fixed ;-). Give me a sec, I will add the "stat" call...

**Comment by telkamp** [comment]
Thank you for your fast support! I will try it.

There is another issue regarding CentOS 7 I would like to talk about. homegear uses a slightly specific version of libphp5.so with ZTS support for the scripting engine. I didn't found a suitable RPM of libphp in the official repositories, so I compiled it for my own (using options ./configure --prefix=/usr --with-config-file-path=/etc --enable-maintainer-zts --enable-embed=shared). 

The required libphp5.so might be the default one for Debian, but for CentOS this is not the case.
To avoid conflicts with an already installed libphp5.so, it might be an option to link the library statically, or to include it in the distribution package. What do you think?

**Comment by spali** [comment]
I stumbled on something similar during some build with the Debian packages. 
They have a suffix homegear in the name, but use the default path for Installation. So it conflicts anyway with other installed versions. 
To solve both I suggest to use install locations suffixed with homegear. For the libraries names too. 
Changing the install path of the binaries, libs and config shouldn't be to much effort, also linking homegear against this. Then homegear can co-exist with anyway other stuff. 
@Sathya what do you think?

**Comment by hfedcba** [comment]
I already quickly tried to link PHP statically - there was a problem, but I can't remember what it was. In general I think the static linking is the best solution. Maybe the settings path needs to be changed, too (I will check all paths). The module path shouldn't matter as it already is specific for one version.
