### ISSUE TITLE
corrupted double-linked list: error while starting with init script

### ISSUE THREAD

**Issue by andreasotto** [Homegear/Homegear#237]
While starting with the init-script `/etc/init.d/homegear start` the following happens:

```
Okt 15 23:34:31 debian homegear[816]: chmod: Zugriff auf „/var/lib/homegear/firmware“ nicht möglich: Datei oder Verzeichnis nicht gefunden
Okt 15 23:34:31 debian homegear[816]: chmod: Zugriff auf „/var/lib/homegear/firmware/*“ nicht möglich: Datei oder Verzeichnis nicht gefunden
Okt 15 23:34:31 debian homegear[816]: chmod: Zugriff auf „/var/lib/homegear/firmware/GetFirmwareUpdates.sh“ nicht möglich: Datei oder Verzeichnis nicht gefunden
Okt 15 23:34:31 debian homegear[816]: Starting Homegear: homegear*** Error in `/usr/bin/homegear': corrupted double-linked list: 0x00000000021e1ae0 ***
Okt 15 23:34:31 debian homegear[816]: /etc/init.d/homegear: Zeile 51:   837 Abgebrochen             start-stop-daemon --start --quiet --oknodo -c $RUNASUSER -g $RUNASGRO
Okt 15 23:34:31 debian homegear[816]: failed!
Okt 15 23:34:31 debian systemd[1]: homegear.service: control process exited, code=exited status=134
Okt 15 23:34:31 debian systemd[1]: Failed to start LSB: Start Homegear.
-- Subject: Unit homegear.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit homegear.service has failed.
-- 
-- The result is failed.
Okt 15 23:34:31 debian systemd[1]: Unit homegear.service entered failed state.
```

Thats why restart or stop doesn't work. Killing the process manually works.

Debian 8, nightly build from Oct. 10th

**Comment by hfedcba** [comment]
Fixed in current version

**Comment by renmarq** [comment]
Hi,

I'm having a similar issue when starting homegear on Raspbian Stretch:

root@raspberrypi:/home/pi# /usr/bin/homegear -u homegear -g homegear -p /var/run/homegear/homegear.pid -pre
*** Error in `/usr/bin/homegear': corrupted double-linked list: 0x020eedf8 ***
Aborted

||/ Name                          Version             Architecture        Description
+++-=============================-===================-===================-===============================================================
ii  homegear                      0.7.30-1900         armhf               Interface program to your smart home devices

Should I open a separate issue? Thank you.

**Comment by renmarq** [comment]
Please forget my previous comment. Issue was fixed by doing and "apt upgrade". Hope this can help someone else.
