### ISSUE TITLE
External mqtt based temperature sensor for hm-cc-rt-dn

### ISSUE THREAD

**Issue by friendofg** [Homegear/Homegear#239]
It would be nice to use an external non homematic temperature for sensor to set the current state for the temperature instead using the hm-cc-rt-dn built-in temperature sensor.
Proposal: Use the mqtt interface of homegear 0.6

references:
https://forum.homegear.eu/viewtopic.php?f=23&t=361
https://forum.homegear.eu/viewtopic.php?f=15&t=382 

see also:
http://www.fhemwiki.de/wiki/HM-CC-RT-DN_Funk-Heizk%C3%B6rperthermostat#Simulation_von_Fensterkontakten_und_externen_Temperatursensoren
http://forum.fhem.de/index.php/topic,17598.msg118163.html#msg118163

**Comment by hfedcba** [comment]
I probably won't have time to implement this in the near future. But I'm happy to support anybody who wants to do this.
