### ISSUE TITLE
connection to hm-cfg-lan failed

### ISSUE THREAD

**Issue by Pedda83** [Homegear/Homegear#240]
I can't get connection to my hm-cfg-lan at version:
Homegear version 0.6.0-1053

there is the following entry in homegear.log:
Module HomeMatic BidCoS: LAN-Konfigurationsadapter "LEQXXXXXXX": Error in file PhysicalInterfaces/HM-CFG-LAN.cpp line 812 in function void BidCoS::HM_CFG_LAN::listen(): Could not connec
t to server 192.168.XXXXXX on port 1000. Poll failed with error code: 1.

**Comment by hfedcba** [comment]
The log shows no error in Homegear. It just can't connect. The TCP connection cannot be initiated for the following reasons:

* Wrong IP-Address
* HM-CFG-LAN is not reachable (routing problem, firewall, ...)
* Another device is connected to the HM-CFG-LAN (check if port 1000 is open with a port scanner)
* The HM-CFG-LAN is broken

Cheers,

Sathya
