### ISSUE TITLE
Error: Server could not start listening on port 80: Permission denied

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#241]
after solving #199 still seems to be that the port of the default web-server (port 80) still is tried to be opened by the user homegear, which doesn't have permissions of course.
```RPC Server (Port 80): Error: Server could not start listening on port 80: Permission denied```

build: 0.6.0-1054

clean homegear install of 0.6.0-1056 with just uncommented the WebServer1 config in rpcservers.conf

**Comment by hfedcba** [comment]
Now you can listen on ports lower than 1025 ;-).
