### ISSUE TITLE
Insecure download over HTTP in debian/postinst

### ISSUE THREAD

**Issue by markuslindenberg** [Homegear/Homegear#242]
Hi, 

thanks a lot for Homegear :)

There's an insecure `wget` call in the Debian postinst script:
https://github.com/Homegear/Homegear/blob/master/debian/postinst#L32

As the homegear.eu site (optionally :( ) uses HTTPS I guess this could easily be changed to HTTPS without issues.

Also, in the Wiki instructions at https://www.homegear.eu/index.php/Downloads the links to `Release.key` and nightly packages are HTTP not HTTPS without fingerprints/checksums to validate against. 

Let's not make it easy for the man in the middle. Ever.

**Comment by hfedcba** [comment]
The reason was, that I used a certificate from StartSSL, which sometimes caused the SSL handshake to fail, because OSCP returned garbage. I now switched to Let's Encrypt (because you created the issue. Thanks :+1:!!!) and hope those problems are gone for good.

**Comment by Wirrkopf76** [comment]
I have just tried to apt-get update and first got the following error message:

E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?

After installing apt-transport-https I can do apt-get update, but get the following error regarding homegear.eu

W: Failed to fetch http://homegear.eu/packages/Raspbian/jessie/Packages  Could not resolve host: homegear.eupackages

Do you have a https redirect configured which is not working correctly? All has been going well before. And I think it might have something to do with this change.

**Comment by Wirrkopf76** [comment]
After manually changing 

from http://homegear.eu ........
to https://homegear.eu ........

in /etc/apt/sources.list.d/homegear.list everything works as expected. 

But you might have broken update for anybody not manually changing the sources file

btw. that's raspbian 8

**Comment by hfedcba** [comment]
Now (for now) http is allowed again! Thanks!
