### ISSUE TITLE
Download of PHP_XMLRPC_Client fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by leifbladt** [Homegear/Homegear#243]
I tried to install homegear on Ubuntu 14.04, but it fails when downloading the XMLRPC client. The server sends a new location (with https), which is obviously broken (a slash is missing after homegear.eu).

```
--2015-12-28 15:23:24--  http://homegear.eu/downloads/Homegear_PHP_XMLRPC_Client.zip
Resolving homegear.eu (homegear.eu)... 62.75.235.71
Connecting to homegear.eu (homegear.eu)|62.75.235.71|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://homegear.eudownloads/Homegear_PHP_XMLRPC_Client.zip [following]
```

Maybe this is related to #242.

**Comment by toO231** [comment]
the same problem here :(

**Comment by hfedcba** [comment]
I enabled HSTS and Public Key Pinning and for that redirected http://homegear.eu to https://homegear.eu - forgetting the slash... I didn't realize it, because version 0.6 is using https by default. Thanks for reporting the issue! It should work now.

**Comment by leifbladt** [comment]
:+1:
