### ISSUE TITLE
Illegal instruction on Jessie

### ISSUE THREAD

**Issue by cribskip** [Homegear/Homegear#244]
Hi,

last week I upgraded wheezy on my Raspberry to Jessie and all was working fine with homegear. Today I noticed a new version of homegear and upgraded to 0.5.25-1 which broke my installation.

Starting homegear results in a core dump caused by an illegal instruction:
```
root@openhab:/tmp# homegear
12/30/15 18:38:43.683 Loading RPC server settings from /etc/homegear/rpcservers.conf
12/30/15 18:38:43.685 Loading RPC client settings from /etc/homegear/rpcclients.conf
12/30/15 18:38:43.686 Info: Loading family module mod_miscellaneous.so
12/30/15 18:38:43.694 Info: Loading family module mod_homematicbidcos.so
12/30/15 18:38:43.708 Info: Loading family module mod_max.so
12/30/15 18:38:43.720 Info: Loading family module mod_homematicwired.so
12/30/15 18:38:43.730 Info: Loading family module mod_philipshue.so
12/30/15 18:38:43.739 Info: Loading family module mod_insteon.so
12/30/15 18:38:43.789 Module HomeMatic BidCoS: LAN-Konfigurationsadapter "My-HM-CFG-LAN": Info: Disabling AES encryption for communication with HM-CFG-LAN.
12/30/15 18:38:43.789 Initializing database...
12/30/15 18:38:43.796 Initializing family controller...
12/30/15 18:38:43.797 Module HomeMatic BidCoS: Loading XML RPC devices...
12/30/15 18:38:44.626 Info: Not initializing device family HomeMatic Wired, because no physical interface was found.
12/30/15 18:38:44.626 Info: Not initializing device family INSTEON, because no physical interface was found.
12/30/15 18:38:44.626 Info: Not initializing device family MAX!, because no physical interface was found.
12/30/15 18:38:44.626 Info: Not initializing device family Philips hue, because no physical interface was found.
12/30/15 18:38:44.626 Module Miscellaneous: Loading XML RPC devices...
12/30/15 18:38:44.628 Loading devices...
12/30/15 18:38:44.629 Module HomeMatic BidCoS: Loading HomeMatic BidCoS device 1
Illegal instruction (core dumped)
```

I even deleted my device DB but with the same result.

What can I do to provide you with more information?
Do you need the core dump?
May I test anything else?

Thanks,
Sascha

**Comment by hfedcba** [comment]
Did you change the Homegear repository from wheezy to jessie in /etc/apt/sources.list.d/homegear.list? Did you try to reinstall Homegear? There hasn't been any new 0.5 Homegear version for a while so it should work.

**Comment by cribskip** [comment]
Thanks for your reply.

Yep, I tried reinstalling and my repo is:
```
root@openhab:/etc/apt/sources.list.d# cat homegear.list 
deb https://homegear.eu/packages/Debian/ jessie/
```

**Comment by cribskip** [comment]
First, Happy New Year :)

Ok, I'll close. Jessie must have had a change in gnutls-libs. While compiling from source, make complained about this.

Compiling resulted fine, just following your great documentation [[https://www.homegear.eu/index.php/Installing_and_Configuring_Homegear#Installing_from_Source]] yielded:

´´´
root@openhab:/usr/src/homegear/homegear-0.5.25# service homegear status
● homegear.service - LSB: Start Homegear
   Loaded: loaded (/etc/init.d/homegear)
   Active: active (running) since Fr 2016-01-01 16:20:33 CET; 4s ago
  Process: 25376 ExecStop=/etc/init.d/homegear stop (code=exited, status=0/SUCCESS)
  Process: 26002 ExecStart=/etc/init.d/homegear start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/homegear.service
           └─26026 /usr/bin/homegear -p /var/run/homegear/homegear.pid -d
´´´

THANK YOU
