### ISSUE TITLE
homegear.sock created with wrong permissions

### ISSUE THREAD

**Issue by mnlipp** [Homegear/Homegear#245]
According to https://forum.homegear.eu/viewtopic.php?t=40 it should be possible to run "homegear -r" as member of group homegear. However, homegear.sock is created with permissions

`srwxr-x--- 1 homegear homegear 0  6. Jan 12:33 /var/run/homegear/homegear.sock`

After doing a `chmod g+w` I can access the server.

(Version 0.5.25)

**Comment by hfedcba** [comment]
Thanks! You're right, 750 doesn't make a lot of sense. I changed this now to 770 (in Homegear 0.6).

Cheers,

Sathya
