### ISSUE TITLE
curl extension in php script engine

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#247]
If I'm not wrong, curl extension is not included in the php script engine.
Would it be possible to include it?

**Comment by hfedcba** [comment]
It's not included, because that got complicated in Debian Wheezy. Now that Jessie is stable, I don't see why not. Let me see, what I can do ;-).

**Comment by spali** [comment]
jessie is fine, I should update anyway to it.

**Comment by hfedcba** [comment]
Will be in the next version ;-).
