### ISSUE TITLE
enhancement: package installation stability

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#248]
I had a total outage due a hardware error last week.
I tried to reinstall an older homegear debian package. The problem was, that it tried to download firmware files which didn't exist anymore on e3 server.
Probably it would be more error prone to download the firmware files as part of the running homegear service (probably as separated module). I would also make the links configurable in a config file to allow updating the download links. And probably also how to extract the files in case they changed the structure (but this would be bit more complicated to implement it enough flexible).

With this enhancement, homegear would not rely on links which you don't have under control for installation. This would allow to install older packages without problems and then configure the new download url which theoretically also could be local (from a data backup).
Also "live" updates would be possible to be implemented.

**Comment by hfedcba** [comment]
In 0.6 Homegear doesn't depend on the success of the firmware download anymore. As 0.6 is stable now, I'm closing this issue.

The "live" update is not configurable, but possible already by just placing the firmware files in the firmware update directory.
