### ISSUE TITLE
eq-3 download link not found

### ISSUE THREAD

**Issue by cribskip** [Homegear/Homegear#249]
Hi,

while  installing, fetching the homematic firmware http://www.eq-3.de/Downloads/Software/HM-CCU2-Firmware_Updates/HM-CCU2-2.11.6/HM-CCU-2.11.6.tar.gz fails because of HTTP 404.

New link is http://www.eq-3.de/Downloads/Software/HM-CCU2-Firmware_Updates/HM-CCU2%202.17.16/HM-CCU-2.17.16.tar.gz

Thanks

EDIT: Found this on the forum already showing a solution. https://forum.homegear.eu/viewtopic.php?f=14&t=590. Thank you guys

**Comment by hfedcba** [comment]
Just fixed it ;-).
