### ISSUE TITLE
homegear not started using systemd

### ISSUE THREAD

**Issue by avanc** [Homegear/Homegear#252]
I'm using the service file from here: https://github.com/Homegear/Homegear/blob/1c0dd0cd3d46e950e1fa3ca5760a82acd38a2861/misc/System%20Config/homegear.service

However, it always stops immediately after startup with signal 15.
[systemd_log.txt](https://github.com/Homegear/Homegear/files/321627/systemd_log.txt)

As an interesting side note, I wonder why homegear is complainig to start as root, although it ist configured with -u homegear.

I also tried to using a systemd service of type _simple_ without daemon mode of homegear. However, this gives the same result.

Starting homegear from command line works without problems.

**Comment by avanc** [comment]
Some additions. In general, systemd prefers services with Type=simple. However, homegear fails if started in an non-interactive envicronment:
`homegear </dev/null >noninteractive.txt 2>&1`

[noninteractive.txt](https://github.com/Homegear/Homegear/files/321628/noninteractive.txt)

I guess if this is solved, starting homegear from systemd would work as Type=simple.

**Comment by hfedcba** [comment]
ok, thanks. That really helps. I will look into it.

**Comment by hfedcba** [comment]
The problem indeed was that Homegear didn't run in non-interactive mode. Now everything is working ;-). Thanks!

**Comment by avanc** [comment]
Thanks, latest software is working with systemd in simple mode.

BTW, if your write something like

    Fix #252

in your commit message, github will recognize it and will link the corresponding commit into the ticket.
