### ISSUE TITLE
Compiler error: No member named ‘getDirectories’

### ISSUE THREAD

**Issue by avanc** [Homegear/Homegear#254]
While compiling the latest commits, I get the following error:

    main.cpp: In function ‘int main(int, char**)’:
    main.cpp:1204:52: error: ‘class BaseLib::Io’ has no member named ‘getDirectories’; did you mean ‘isDirectory’?
      std::vector<std::string> subdirs = GD::bl->io.getDirectories(currentPath, true);

**Comment by hfedcba** [comment]
Have you recompiled libhomegear-base? getDirectories was added pretty recently.

**Comment by avanc** [comment]
Sure, I recompiled libhomegear...
... but I forgot to install it ;-)

Thanks for the hint!
