### ISSUE TITLE
Non standard conform system.listMethods calls

### ISSUE THREAD

**Issue by Koshu** [Homegear/Homegear#256]
As promised. Just a little bug and probably not even that important. Homegear calls the listMethod function of an xmlrpc-client with an additional parameter that isn't in the standard, causing the client to throw exceptions. I think the additional parameter is the "id". 

```
07/04/16 19:07:31.006 RPC client: Error in RPC response from 127.0.0.1. faultCode: 1 faultString: <class 'TypeError'>:system_listMethods() takes 1 positional argument but 2 were given
07/04/16 19:07:31.007 Warning: Error calling XML RPC method "system.listMethods" on server http://127.0.0.1 with port 8222. Error struct: 
```

I guess this is bug? Or does the CCU behave the same?

**Comment by hfedcba** [comment]
The CCU accepts both. As it is not necessry I removed the argument.
