### ISSUE TITLE
Error on linking Philips Hue since April 2016

### ISSUE THREAD

**Issue by codmpm** [Homegear/Homegear#257]
Hi Sathya,

sadly I can not link my new Hue Bridge with homegear as the method used by homegear is no longer supported by the Hue. See http://www.developers.meethue.com/documentation/important-whitelist-changes.

Homegear set to debug level 5 shows that it tries to register a username:
`{"devicetype":"Homegear","username":"homegearMy-Bridge-1234"}`

The response from the hue bridge is as follows:
`[{"error":{"type":6,"address":"/username","description":"parameter, username, not available"}}]`

As shown on the meethue page one should not give the bridge a username anymore but instead take the one it gives back in it's response.

Hope this info helps to get it working again.
Thank you so much for your work.

Regards,
Patrik

**Comment by iWampy** [comment]
H Patricki,
@hfedcba fixed this in Release [0.6.3](https://github.com/Homegear/Homegear/releases/tag/0.6.3)

Greetings

**Comment by hfedcba** [comment]
Yes, it's fixed now ;-).

**Comment by torstenboe** [comment]
Hm, doesn't work for me :-(
I have used the API Debugger to create a username and used that in philipshue.conf. Still Hue doesn't show up in families

**Comment by hfedcba** [comment]
If it doesn't show up in families the error is not related to the problem described here. What does your "philipshue.conf" look like?

**Comment by torstenboe** [comment]
Hi Sathya,


many thanks for your help. Please the conf attached. I have also installed other interfaces (SONOS, Homematic) and these seem to work just fine.


Best

Torsten


________________________________
Von: Sathya Laufer <notifications@github.com>
Gesendet: Donnerstag, 22. September 2016 14:11
An: Homegear/Homegear
Cc: torstenboe; Comment
Betreff: Re: [Homegear/Homegear] Error on linking Philips Hue since April 2016 (#257)


If it doesn't show up in families the error is not related to the problem described here. What does your "philipshue.conf" look like?

-

**Comment by hfedcba** [comment]
There is no attachment ;-). GitHub seems to delete it from mails. Just post the content of the config here.

**Comment by torstenboe** [comment]
___________________________________________________________________________

------------------------------- Philips hue -------------------------------
___________________________________________________________________________

[General]

#######################################
############# Hue Bridge  #############
#######################################

## The device family this interface is for
#[Hue Bridge]

## Specify an unique id here to identify this device in Homegear
## This identifier is also used as the bridge user name and "password".
id = Svxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxmd

## Options: huebridge
deviceType = huebridge

## IP address of your bridge
host = 192.xxx.xx.xx

## Port number your bridge listens on. Normally 80.
port = 80

## Should be "100" for Philips hue
responseDelay = 100

# The interval in milliseconds to poll the Hue bridge
interval = 15000

**Comment by hfedcba** [comment]
Remove the "#" in front of "[Hue Bridge]". Then it'll work.

**Comment by torstenboe** [comment]
Many thanks - that was it. Is working now.
