### ISSUE TITLE
addEvent: Add optional parameter to force overwriting of existing rule

### ISSUE THREAD

**Issue by avanc** [Homegear/Homegear#260]
To avoid an additional "removeEvent" in front of some rules. it should be possible to overwrite existing rules:

```
$hg->addEvent(
  array(
    "ID" => "MyEvent",
    "replace" => true,
    ....
```

**Comment by avanc** [comment]
Without this, distributing scripts becomes very irritating.
If I provide a script like the following to someone else, it will fail:

    $hg->removeEvent("MyEvent");
    $hg->addEvent(
      array(
        "ID" => "MyEvent",
        ...

However, the following script will when it is executed several times:

    $hg->removeEvent("MyEvent");
    $hg->addEvent(
      array(
        "ID" => "MyEvent",
        ...

Thus, the additional "replace" parameter or forceAdd would be very helpfull.

**Comment by hfedcba** [comment]
Done.
