### ISSUE TITLE
GPIO permission denied error if non-default GPIO pins are used

### ISSUE THREAD

**Issue by nohum** [Homegear/Homegear#261]
I am using the non-default GPIO pins 22 and 23 with a COC because the default pins 17 and 18 are already used for some other communication chip. My COC configuration living in the file `homematicbidcos.conf` looks like the following:

```
[COC]
id = default-coc
default = true
deviceType = coc
device = /dev/ttyAMA0
responseDelay = 95
gpio1 = 22
gpio2 = 23
stackPosition = 0
``` 

Running homegear using the default homegear user and group fails as Homegear is not able to open the GPIO files (log output of homegear.err):

```
08/29/16 20:44:31.245 Error in file Systems/IPhysicalInterface.cpp line 331 in function virtual void BaseLib::Systems::IPhysicalInterface::openGPIO(uint32_t, bool): Failed to open GPIO value file "/sys/class/gpio/gpio23/value": Permission denied
08/29/16 20:44:31.245 Failed to set GPIO with index "2": Device not open.
08/29/16 20:44:31.245 Failed to set GPIO with index "2": Device not open.
08/29/16 20:44:31.246 Error in file Systems/IPhysicalInterface.cpp line 331 in function virtual void BaseLib::Systems::IPhysicalInterface::openGPIO(uint32_t, bool): Failed to open GPIO value file "/sys/class/gpio/gpio22/value": Permission denied
08/29/16 20:44:31.246 Failed to set GPIO with index "1": Device not open.
08/29/16 20:44:31.246 Failed to set GPIO with index "1": Device not open.
08/29/16 20:44:32.246 Failed to set GPIO with index "1": Device not open.
```

Note: The pins are however hooked up correctly to the COC as running homegear as root works flawlessly (tested by editing the service start files with v0.6.3). In the current version 0.6.7 starting as root seems not to work any more as user id 0 and group id 0 are filtered out and an error is printed (`Could not drop privileges. User name or group name is not valid.`)

Before starting Homegear I have a script in place which makes the pins 22 and 23 writable which seems to work as the user and group of the GPIO files are set correctly after that (user root and group gpio):

```
gpio export 22 out
gpio export 23 out

# COC init
echo 1 > /sys/class/gpio/gpio23/value
echo 0 > /sys/class/gpio/gpio22/value
sleep 1
echo 1 > /sys/class/gpio/gpio22/value
sleep 1
```

So the permissions seem to be correct (the homegear user is a member of the gpio group) but still it the daemon is not able to access the GPIOs.

**Comment by hfedcba** [comment]
Hey,

I fixed the problem that Homegear doesn't start as root (I assume you set "-u root -g root"?). The COC should work without root privileges though. Have you followed the instructions here: https://doc.homegear.eu/data/homegear-homematicbidcos/configuration.html#config-coc? Most importantly: Are you using the official Raspbian and did you delete the file "/etc/udev/rules.d/99-com.rules"?

Cheers,

Sathya

**Comment by nohum** [comment]
> I fixed the problem that Homegear doesn't start as root (I assume you set "-u root -g root"?).

Thanks! Yes, I'm using "-u root -g root". 

> Are you using the official Raspbian and did you delete the file "/etc/udev/rules.d/99-com.rules"?

Yes, I'm using an official Raspbian image. I followed the setup instructions back when installing Homegear for the first time ... but somehow it seems I forgot to delete the file "/etc/udev/rules.d/99-com.rules".

Removing that file did the trick and it works now - thank you for helping!

**Comment by hfedcba** [comment]
Great, it works now ;-).
