### ISSUE TITLE
Configureable RpcClient retry and reconnectInfinitely

### ISSUE THREAD

**Issue by infernix** [Homegear/Homegear#263]
As per $subject, it would be great if we can configure these values. I am currently debugging an issue where HASS->pyhomematic->homegear breaks for unknown reasons after 3 retries and by being able to configure the retries I might be able to solve it (if it is an intermittent network issue).

Same for reconnectInfinitely although a configurable retry might be enough; set at high numbers it might practically be the same.

**Comment by infernix** [comment]
To clarify this further: if the RpcClient can't send its packets, it retries 3 times and then gives up saying the server has to send "init" again.

I would like to be able to configure the retry attempts in this case to accommodate for bad network reception (wifi) so that the connection is more reliable.

**Comment by hfedcba** [comment]
There is a new setting "retries" in rpcclients.conf now. The maximum value is "20" though as an infinite retry might cause a lot of problems.
