### ISSUE TITLE
Homegear mipsel

### ISSUE THREAD

**Issue by promille** [Homegear/Homegear#264]
I need to build homegear for a misel structure. I have successfully compiled the php7 and base lib part.
But now homegear throws an error ... Only ARM, AARCH64, x86 and x86-64 are supported

What is the purpose of this restriction?

**Comment by promille** [comment]
`--- Homegear-master/src/DeathHandler.cpp        2016-11-07 18:53:03.000000000 +0000
+++ Homegear-master-orig/src/DeathHandler.cpp   2016-10-25 08:10:34.000000000 +0100
@@ -575,7 +575,7 @@
 #ifdef __linux__
 #if defined(__arm__)
   trace[1] = reinterpret_cast<void *>(uc->uc_mcontext.arm_pc);
-#elif defined(__aarch64__) || defined(__mips__)
+#elif defined(__aarch64__)
   trace[1] = reinterpret_cast<void *>(uc->uc_mcontext.pc);
 #else
 #if !defined(__i386__) && !defined(__x86_64__)`

**Comment by hfedcba** [comment]
Hey, the DeathHandler prints stack traces into the error log. It isn't really needed for Homegear to run. Try to compile the dev-Branch now. It should work. Please send me a feedback if Homegear works on mipsel.

**Comment by hei-pa** [comment]
I was able to build homegear with the patch given above. Are there any other changes in the dev branch?

**Comment by hfedcba** [comment]
I just merged the dev branch, so for the moment they are the same.
