### ISSUE TITLE
Feature request: Add publish( ) method to built-in PHP

### ISSUE THREAD

**Issue by pfandfrei** [Homegear/Homegear#268]
In case homegear is connected to a MQTT broker it would be great to have the ability to publish direct to the MQTT broker. This would be easier than connecting and publich with a separate PHP-MQTT client in scripting.

**Comment by hfedcba** [comment]
Done. Example usage from console:

homegear -e rc '$hg->mqttPublish("MyTopic", "{\"value\": 5}");'
