### ISSUE TITLE
Make database backup path configurable

### ISSUE THREAD

**Issue by manuelm** [Homegear/Homegear#269]
Database writes are hurting disk endurance especially if running from a sdcard/usb stick. Right now I'm using a tmpfs as `dataPath` and run rsync on a daily basis and on shutdown to backup the database files to persistent storage. This process would be a bit easier if the directory for the database backups could be specified. For example I could store them on an extra usb stick which only serves for backups.

I can do a PR in case you're interested

**Comment by hfedcba** [comment]
> Database writes are hurting disk endurance especially if running from a sdcard/usb stick

True.

> This process would be a bit easier if the directory for the database backups could be specified.

It's a good idea to make the database backup path configurable. Let me do that quickly, it's a matter of 5 minutes ;-).

**Comment by hfedcba** [comment]
Done ;-).

**Comment by manuelm** [comment]
Thank you very much
