### ISSUE TITLE
[Enhancement]Filter for subscribePeer

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#276]
Currently it is only possible to subscribe to a whole peer with `subscribePeer()` which does sometimes generate a lot of unwanted events with `pollEvent` that probably are not required. To reduce the load it would be great to support more detailed subscribe to events.
i.e. per parameter and with changed / updated like in the `EventDescription`.

**Comment by hfedcba** [comment]
Documentation is now up to date, too: https://ref.homegear.eu/php.html#HomegearsubscribePeer
