### ISSUE TITLE
[Bug/Enhancement]Exception in virtual device main thread with running event thread can hang up homegear

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#277]
I'm not 100% sure about the exact reason of the problem, but from my debuging looks like the following could portentially hang up the event handling of homegear:
as an example in OpenWeatherMap, when an unhandled error occurs after starting the event-thread (i.e. in the while loop), the event thread is still running and the the main thread waits with `join()` for the event thread. But somehow in my situation this locks the event handling of homegear... during this hang no events of my devices are processed and also invoke setValue on devices with homegear cli just hangs.
If i enclose the line which produced the unhandled error with `try` `catch` and just prevent the exception to be thrown it it will just run as expected. ~~Another workaround was to remove the `join()` to the event thread, which would homegear let the device "restart"~~.

As written, still not 100% sure about the exact situation, but probably there is somewhere a raise condition which is not handler by homegear.
If you can't reproduce it, I will try to reduce it to a minimal testcase as soon as I have time. In this case just keep the issue on hold to remember this.

Edited: on workaround doesn't seem to work always

**Comment by spali** [comment]
It seems to make a difference if it is a thrown exception, which can be catched with a `try {} catch {}` or if it is  non handled error like fatal error. This has to be explicitly handled with `set_error_handler()`.
currently I  set the error handler and just throw expections for all errors. Which seems to work really good as long the exceptions in the thread loops are handled and just output the error.
Probably this could be included in homegear script engine to explicitly define an default error handler for all exceptions and just throw them like `throw new ErrorException(....)` and make shure in this case to just restart the device script in case it is defined as `permanent`. This would prevent hanging up anything if it is not handled by the script itself.

**Comment by hfedcba** [comment]
> as an example in OpenWeatherMap, when an unhandled error occurs after starting the event-thread (i.e. in the while loop), the event thread is still running and the the main thread waits with join() for the event thread. But somehow in my situation this locks the event handling of homegear...

Could you please check if that still is the case? I can't seem to reproduce the issue. If the error still occurs, could you send me the script?

**Comment by spali** [comment]
Can't reproduce it currently. Probably fixed with one of the many changes you did :)
