### ISSUE TITLE
[Bug]getAllConfig and getAllValues behaves differently

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#279]
`getAllConfig` and `getAllValues` behaves differently in a way I think shouldn't be the case.

If you have a device with an ACTION parameter in the MASTER (config) of channel 0 and a ACTION parameter in  VALUES of channel 1.
Then `getAllConfig` returns the ACTION parameter of MASTER in channel 0.
But `getAllValues` does not return the ACTION parameter of VALUES in channel 1.

I would expect to see the action of channel 1 in `getAllValues` because it is defined in the values section of the XML.
Or `getAllConfig` should not include the action to be consistent, but then there should be another possibility to get ACTION parameters of MASTER and VALUES.

**Comment by spali** [comment]
By the way... is it possible, that no event is triggered for an action parameter in MASTER channel 0 ?
I tried to implement a "RESTART" action in the device, which let the device exit the loop's in the threads. So that homegear restarts the killed device main thread.  Becuase it's a "low-level" action I thought it would be a good idea to put this in the MASTER of channel 0. 
Currently I have to workaround that limitation and put the action in VALUES.

**Comment by hfedcba** [comment]
Type ACTION is not supported for configuration parameters (MASTER). As configuration parameters are supposed to store a value, ACTION only makes sense for variables (VALUES). I now removed ACTION from `getAllConfig` completely.

> But getAllValues does not return the ACTION parameter of VALUES in channel 1.

That shouldn't be the case. Could you send me an example XML file?

**Comment by spali** [comment]
I added all files, including the PHP code, but probalby you see the problem already within XML.
https://gist.github.com/spali/523727b0f84309befc1aab98653d45da
Currently I need `getParamsetDescription` for each channel to also get the ACTIONS. because `getAllValues` does not return the action RESTART or REQUEST form channel 1 in this example.

**Comment by hfedcba** [comment]
The problem is "<readable>false</readable>". Which is true of course for an ACTION variable. With that statement you are creating a "write only" variable. For `getAllValues()` to return it, you need to set the argument `returnWriteOnlyVariables` to `true`.

**Comment by spali** [comment]
thanks somehow missed that argument exists.
