### ISSUE TITLE
[Enhancement][low-prio]improve scriptsrunning 

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#280]
8a38264e6178a561c0602a87a0e6ac3742badd50
thats a good one, would wish process id and and peer id  would show up too, to identify them for debugging.

because sometimes during homegear shutdown I have log entries like these:
```
03/09/17 13:42:01.838 Script Engine Server: Critical: Client process with pid 9482 was killed with signal 11.
03/09/17 13:42:02.667 Script Engine Server: Error: No or invalid response received to RPC request. Method: shutdown
```

I'm almost sure they are from one of my scripts which does somehow not cleanly shutdown and get's killed.  With this information, I could identify it.

**Comment by hfedcba** [comment]
Done:

```
PID       Peer ID   ID        Filename                                                                        
13276     207       7         /etc/homegear/devices/254/HM-V-PHP-Float.xml
```

**Comment by hfedcba** [comment]
I renamed "ID" to "Script ID"
