### ISSUE TITLE
Running homegear from systemd fails

### ISSUE THREAD

**Issue by avanc** [Homegear/Homegear#281]
I tried to run homegear with the following systemd service file:

```
[Unit]
Description=Homegear server
After=network.target 

[Service]
Type=simple
User=homegear
Group=homegear
UMask=002
TasksMax=infinity
LimitRTPRIO=100
ExecStart=/usr/bin/homegear

[Install]
WantedBy=multi-user.target
```

However, it fails with no additional information. It seemed, that systemd does not get the stdout output as described in: http://askubuntu.com/a/622292

This I changed the service file to:
```
ExecStart=/usr/bin/stdbuf -oL /usr/bin/homegear
```

Surprisingly, homegear starts now without any problems. So I actually don't know what makes homegear under systemd crashing. Maybe it ist stdout?

**Comment by hfedcba** [comment]
Hmm, in general Homegear works with systemd. Does it work with the default file?

```
[Unit]
Description=Homegear
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
PIDFile=/var/run/homegear/homegear.pid
TimeoutSec=300
LimitRTPRIO=100
ExecStartPre=/etc/homegear/homegear-start.sh
ExecStart=/usr/bin/homegear -u homegear -g homegear -p /var/run/homegear/homegear.pid
ExecStopPost=/etc/homegear/homegear-stop.sh
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
TasksMax=infinity
LimitRTPRIO=infinity
LimitRTTIME=infinity
LimitCORE=infinity
```

You shouldn't start Homegear directly as user as Homegear needs root privileges to set some things up. Instead start Homegear with `-u homegear -g homegear`. That drops privileges after everything is set up.

Cheers,

Sathya

**Comment by hfedcba** [comment]
Your systemd file works on a system where Homegear was already started with the default systemd file. So my guess is, some directory is missing (e. g. "/var/log/homegear") or has the wrong permissions set.

**Comment by avanc** [comment]
I changed the ownership to homegear:homegear before. Interestingly, it works without a problem if using /usr/bin/stdbuf.

Can you give me some hints, where root privileges are needed? Maybe it is not needed for all users. E.g. I don't need access to GPIOs.

I feel more comfortable if systemd is managing the privileges of other processes. A small bug could lead to severe issues.

**Comment by avanc** [comment]
I had a closer look into the code. Would it be possible to move all preparations needing root privileges to the code executed with _-pre_?

**Comment by hfedcba** [comment]
> I had a closer look into the code. Would it be possible to move all preparations needing root privileges to the code executed with -pre?

No. Especially listening in privileged ports requires root. There is no other way. All other services listening on ports <= 1024 do the same. What we do is "best practice". If you don't need to listen on privileged ports, you of course can run Homegear completely as user after calling "homegear -pre" as root. My guess is that stdbuf works because "/var/log/homegear" is either missing or has the wrong permissions (or the log files inside have the wrong permissions).

**Comment by avanc** [comment]
I will check. Thanks for your quick response.

**Comment by avanc** [comment]
You were right. I missed one single file with wrong permissions. Now everything works as non-root from systemd.
