### ISSUE TITLE
HomeMaticBidCoS: sendFix behaviour contradicts documentation

### ISSUE THREAD

**Issue by avanc** [Homegear/Homegear#282]
Since the following commit, a fix is send if sendFix is false:
https://github.com/Homegear/Homegear-HomeMaticBidCoS/commit/5f048d7bac9eb479160486cf419432f668171c90

The reason is not clear. However, the documentation should be adapted:
https://github.com/Homegear/Homegear-HomeMaticBidCoS/blob/master/misc/Config%20Directory/homematicbidcos.conf#L94

**Comment by hfedcba** [comment]
Hey,

what exactly should be corrected? The default value is `false` - I just checked again. I changed the behavior of `sendFix`, because it seems the default setting now covers more LAN gateways - I'm not sure about that fact though.

Cheers,

Sathya

**Comment by avanc** [comment]
Hi,

if I see a parameter called _sendSomething_ and it is set to true, I would guess something is send. If sending the fix is needed by more LAN gateways, than I would change the default to true.

But what realy confused me, that the documentation in the configuration says:
    If sent packets are not received by the devices (you get error messages, that packets were not received after 3 retries), set sendFix to true.

This is not valid anymore, as I have to set sendFix to false to send the fix :-)

**Comment by avanc** [comment]
Let me create a pull request, maybe I can make my point more clear.

**Comment by hfedcba** [comment]
`sendFix` sends nothing. It enables a fix needed for sending packets on some LAN gateways. So `sendFix = true` means, `sendFix` is enabled. When setting it to `false` packets are being sent without the fix enabled. Only one setting works.

**Comment by avanc** [comment]
Sorry, I'm still confused.

What is normal/standard? Doing 

    payload.push_back((bidCoSPacket->controlByte() & 0x10) ? 1 : 0)

or not?

Before commit https://github.com/Homegear/Homegear-HomeMaticBidCoS/commit/5f048d7bac9eb479160486cf419432f668171c90, I had to set sendFix=true.
After the commit, I have to set sendFix=false to get the same behaviour as before.
So some user intervention is needed for some people and I want to make sure that not everybody falls into this.

Maybe a note like

    Please note that the meaning of sendFix changed!
    If you had set it to true you have to set it to false now.

in https://github.com/Homegear/Homegear-HomeMaticBidCoS/blob/master/misc/Config%20Directory/homematicbidcos.conf#L98 might help when other people merging old and new configuration others.

**Comment by hfedcba** [comment]
> What is normal/standard? Doing

With `sendFix = true` there is one less byte in the packet.

> Maybe a note like

I added a note ;-).
