### ISSUE TITLE
HomematicBidCoS: Setting RAMP_TIME does not give a feedback

### ISSUE THREAD

**Issue by avanc** [Homegear/Homegear#283]
I set the RAMP_TIME of a dimmer using MQTT:

    homegear/1234-5678-9abc/set/3/1/RAMP_TIME : 60

No MQTT message is send by homegear.
After the ramp is finished, the RAMP_TIME is automatically set back to 0.5. In addition, corresponding MQTT messages are send by homegear:

    homegear/1234-5678-9abc/json/3/1/RAMP_TIME : "[0.5]"

However, I would expect such message also when setting the RAMP_TIME.

**Comment by hfedcba** [comment]
> However, I would expect such message also when setting the RAMP_TIME.

Me, too. It wasn't the case when setting writeonly variables such as RAMP_TIME. Now these variables are published, too.
