### ISSUE TITLE
Could not open directory "/var/lib/homegear/flows/nodes/"

### ISSUE THREAD

**Issue by jipp** [Homegear/Homegear#287]
after upgrading to the latest version 0.7.0-1178 I got this error message in the homegear.log:

06/09/17 10:57:46.457 Error in file Flows/NodeManager.cpp line 258 in function static std::vector<std::shared_ptr<NodeManager::NodeInfo> > NodeManager::getNodeInfo(): Could not open directory "/var/lib/homegear/flows/nodes/"

manually creating the folder and setting the permissions and owner according, the error went away during start.

/var/lib/homegear/flows# ls -l
total 12
drwxrwx--- 2 homegear homegear 4096 Jun  6 21:09 data
drwxrwx--- 2 homegear homegear 4096 Jun  9 11:12 nodes
drwxrwx--- 6 homegear homegear 4096 Jun  9 10:40 www

**Comment by jipp** [comment]
on a fresh install this is not happening.
also I needed to run 'apt-get dist-upgrade' which is always a risk

**Comment by hfedcba** [comment]
The directory is now created automatically. Thanks!
