### ISSUE TITLE
Node-BLUE login not working on read-only distribution

### ISSUE THREAD

**Issue by jipp** [Homegear/Homegear#288]
Hi

I use the read-only distribution. So far all went quite well.
I tried to login using http://homegear:2001/flows/index.php

I succeeded doing so creating the following steps:
-make the filesystem rw
-create folder: /var/lib/homegear/tmp/php
-chmod to: drwxrwx--- 2 homegear homegear 4096 Jun 22 07:15 php

This was indicated by the following logs:
06/22/17 07:02:16.110 Scriptengine (/var/lib/homegear/www/rpc/flows/index.php): PHP Warning:  session_start(): open(/var/lib/homegear/tmp/php/sess_28dea2a4df8541c8ab9c8d4b96384cf7, O_RDWR) failed: Permission denied (13) in /var/lib/homegear/flows/www/user.php on line 6
06/22/17 07:02:16.110 Scriptengine (/var/lib/homegear/www/rpc/flows/index.php): PHP Warning:  session_start(): Failed to read session data: files (path: /var/lib/homegear/tmp/php) in /var/lib/homegear/flows/www/user.php on line 6

after this the session log for the login was able to be written and I cold log in.

unfortunately no node is loaded and the browser showed the following info:
vendor.js:5 GET http://homegear:2001/flows/nodes?_=1498108879826 404 (Not Found)

The folder /var/lib/homegear/flows/nodes is empty.

did I miss anything?

thx
jipp

**Comment by jipp** [comment]
recently updated to  0.7.3-1221

I see this in the error log:
06/22/17 07:54:29.718 Warning: Requested URL not found: /var/lib/homegear/flows/www/vendor/vendor.css
06/22/17 07:54:31.039 Warning: Requested URL not found: /var/lib/homegear/flows/www/static/nodes

**Comment by jipp** [comment]
My fault in a way that I forgot to install homegear-nodes-core, homegear-nodes-extra!
After this it founds some nodes to display!

So the only problem is that login is not possible when working in ro mode.

**Comment by hfedcba** [comment]
That was indeed an error in the readonly image. It's fixed now.
