### ISSUE TITLE
HM-LC-Bl1PBU-FM no status change when manual operated

### ISSUE THREAD

**Issue by m0wlheld** [Homegear/Homegear#290]
I already stated this in the forum, but I actually think it's a bug that has been introduced in early 2017. Please let me know how to confirm this or assist in solving.

From the [Forum](https://forum.homegear.eu/t/HM-LC-Bl1PBU-FM-no-status-change-when-manual-operated/1473):

Let's say I lower the blinds to 90% open (100% is fully open) using Home Assistant's GUI, the following appears in the homegear.log (at log level 5):

```
09/26/17 07:51:25.122 RPC Server (Port 2001): Info: Client number 18 is calling RPC method: setValue (1) Parameters:
(String) NEQ13682XX:1
(String) LEVEL
(Float) 0.9
09/26/17 07:51:25.123 Module HomeMatic BidCoS: Debug: LEVEL of peer 28 with serial number NEQ13682XX:1 was set to B4.
```

Next, I go to homegear's console (homegear -r), select peer 28 and use config print to read the current level:

```
Channel: 1
        {
                [WORKING]: 00
                [LEVEL]: b4
                [INSTALL_TEST]: 00
                [STOP]: 01
                [INHIBIT]: 00
                [DIRECTION]: 00
        }
```

So the Level "B4" is reflected properly. Now I open the the blinds completey using the wall switch and nothing happens in homegear's logfile. Not directly and not after a minute, while other components (heating valves, motion and brightness sensors) continuously report changes.

Using homegear's console the config print of peer 28 also remains unchanges

```
Channel: 1
{
        [WORKING]: 00
        [LEVEL]: b4
        [INSTALL_TEST]: 00
        [STOP]: 01
        [INHIBIT]: 00
        [DIRECTION]: 00
}
```

Only if i use Home Assistant again to open (the already open) blinds using homegear's BidCos emulation, the level value of peer 28 is updated:

```
09/26/17 08:03:56.271 RPC Server (Port 2001): Info: Client number 22 is calling RPC method: setValue (1) Parameters:
(String) NEQ13682XX:1
(String) LEVEL
(Float) 1
09/26/17 08:03:56.272 Module HomeMatic BidCoS: Debug: LEVEL of peer 28 with serial number NEQ13682XX:1 was set to C8.
```

Console:

```
Channel: 1
    {
            [WORKING]: 00
            [LEVEL]: c8
            [INSTALL_TEST]: 00
            [STOP]: 01
            [INHIBIT]: 00
            [DIRECTION]: 00
    }
```

So, my Home Assistant automations that depend on getting the actual position of the blinds fail now. This is something that changed about 3 months ago, because those automation rules previously have been working as expected.

**Comment by hfedcba** [comment]
Hey, if really nothing happens in the log file (please verify that),  there is no packet received from the device (every packet is logged) and it's not a Homegear bug. There just is nothing we can process to get the blind state. If a packet is received, it's not processed probably because of missing information in the device description file.

**Comment by hfedcba** [comment]
To really see what's going on, I need the log entries for about 10 seconds after doing something on the blind actuator (level 4 is enough). Without that I can only guess what's happening.

> 2 out of 10 devices went through the AES off and on again procedure and are now back to "normal".

Are you sure, AES signing is really enabled? The broadcast packets from the blind actuators are never signed - even if signing is enabled (in BidCoS there is never anything encrypted). That's why Homegear ignores them by default when AES is enabled (but that should actually be logged). You can change that behavior by setting "processBroadcastWithAesEnabled" to "true" in homematicbidcos.conf.

**Comment by m0wlheld** [comment]
Well,

actually the missing 8 blinds do report their manually-triggered level changes again, without the need to disable/re-enable AES. Maybe the change on some devices was sufficient to bring the setup back on track. 

Regarding AES: Yes, I am quite sure, that it is enabled as the Homematic WebUI reports it as well as config print on an affected devices:

```
(Peer)> config print
MASTER
{
        Channel: 1
        {
                [TRANSMIT_TRY_MAX]: 06
                [STATUSINFO_MINDELAY]: 04
                [REFERENCE_RUN_COUNTER]: 00
                [REFERENCE_RUNNING_TIME_TOP_BOTTOM]: c8
                [REFERENCE_RUNNING_TIME_BOTTOM_TOP]: c8
                [STATUSINFO_RANDOM]: 01
                [CHANGE_OVER_DELAY]: 05
                [AES_ACTIVE]: 01
``` 

Anyhow, the issue is somehow solved. Thanks for your assistance.

Gruß

Christoph

**Comment by hfedcba** [comment]
Nice, that it works again :slightly_smiling_face:.

> Maybe the change on some devices was sufficient to bring the setup back on track.

No. That shouldn't have changed anything.

> Regarding AES: Yes, I am quite sure, that it is enabled as the Homematic WebUI reports it as well as config print on an affected devices:

It's still possible that the configuration is not transmitted. ``queues info`` and the variable ``CONFIG_PENDING`` tell you, if there are any packets still queued. Without ``processBroadcastWithAesEnabled`` being set to ``true`` the broadcast packets shouldn't be processed. I hope that is not the case - that would be a bug.

Cheers,

Sathya
