### ISSUE TITLE
libmariadbclient.so.18: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Azimoth** [Homegear/Homegear#291]
Hi,

since yesterdays MariaDB update (to 10.2.9 on Debian Stretch using the [MariaDB repository](https://downloads.mariadb.org/mariadb/repositories/#mirror=rackspeed&distro=Debian&distro_release=stretch--stretch&version=10.2)), I get this error message when starting homegear:

`libmariadbclient.so.18: cannot open shared object file: No such file or directory`

I found in the [changelog](https://mariadb.com/kb/en/library/mariadb-1029-changelog/) that there was something fixed regarding libmariadbclient, but I cannot extract the information I would need to fix it myself from it.

Is this a MariaDB bug or would a homegear patch be required?

**Comment by hfedcba** [comment]
Hey @Azimoth,

I'm on vacation right now. But as soon as I'm back I will check what is wrong there. Does the file "libmariadbclient.so.18" still exist on your system?

Cheers,

Sathya

**Comment by Azimoth** [comment]
Nope, I was not able to locate a file of that name, however:

```
sudo find / -iname libmariadbclient*
/var/lib/dpkg/info/libmariadbclient18.md5sums
/var/lib/dpkg/info/libmariadbclient18.list
/var/cache/apt/archives/libmariadbclient18_10.2.8+maria~stretch_amd64.deb
/var/cache/apt/archives/libmariadbclient18_10.2.9+maria~stretch_amd64.deb
/var/cache/apt/archives/libmariadbclient18_10.2.6+maria~stretch_amd64.deb
```
And
```
Paket: libmariadbclient18                       
Version: 10.2.9+maria~stretch
Zustand: Installiert
```
So I don't know where it went...

**Comment by hfedcba** [comment]
On my system the file still exists. Also according to the Debian webpage, it should be in the package libmariadbclient18:

https://packages.debian.org/search?searchon=contents&keywords=libmariadbclient.so.18&mode=path&suite=stable&arch=amd64

So the problem probably lies in your system. Does `apt install --reinstall libmariadbclient18` help?

Cheers,

Sathya

**Comment by Azimoth** [comment]
It did, thank you. I tried reinstalling mariadb-server, but that didn't fix it and I was hesitating to (re)install "random" packages in fear of breaking something due to an incompatibility between versions.

How would I have found out, that libmariadbclient18 is still supposed to be there and hence could be reinstalled without any problems?

**Comment by hfedcba** [comment]
> How would I have found out, that libmariadbclient18 is still supposed to be there and hence could be reinstalled without any problems?

As the error message says, "libmariadbclient.so.18" is missing, first look on debian.org which package contains this file. In this case it is "libmariadbclient18". Then use "dpkg-query" to check if this package is supposed to be installed. If it is, something deleted the file accidentally.
