### ISSUE TITLE
MQTT not working if prefix has more than one topic level

### ISSUE THREAD

**Issue by krauskopf** [Homegear/Homegear#294]
Hi, 

In the mqtt.conf one has the possibility to set the prefix for the topics of the mqtt publish/subscribe messages. By default this value is 'homegear'. 

If you change this value to have more than one topic level. E.g. to 'aaa/bbb', then this is accepted by homegear and also the published messages are still working. 
Unfortunately setting a variable will then no longer work. 

This is probably, because in mqtt.cpp there are some fragments, where the topic level is hard coded. E.g. in line https://github.com/Homegear/Homegear/blob/47a108100b9bd8bc4b0d384dfe5e6940a26a9122/src/MQTT/Mqtt.cpp#L577

`		std::vector<std::string> parts = BaseLib::HelperFunctions::splitAll(topic, '/');
		if(parts.size() == 6 && (parts.at(2) == "value" || parts.at(2) == "set"))
`

The code should be changed, so that either a multi-level prefix is working under all conditions or a multi-level prefix is rejected during parsing of the config file (including a warning).

The constraint should also be mentioned in the documentation.

**Comment by hfedcba** [comment]
Hello @krauskopf,

thanks! I now changed the code so multiple parts (and also an empty prefix) work.

Cheers,

Sathya

**Comment by krauskopf** [comment]
Thanks for the fast fix. :-)
