### ISSUE TITLE
"Critical: Unknown database version: 0.7.1" with 0.8.0-2171

### ISSUE THREAD

**Issue by GreSuh** [Homegear/Homegear#299]
After Upgrade from 0.8.0-2125 to (0.8.0-2171) Homegear no longer starts.
With message: 

root@hassbian:/var/log/homegear# homegear
04/14/18 16:28:19.280 Debug: debugLevel set to 10
04/14/18 16:28:19.281 Debug: memoryDebugging set to 1
04/14/18 16:28:19.281 Debug: devLog set to 1
04/14/18 16:28:19.281 Debug: enableCoreDumps set to 1
04/14/18 16:28:19.281 Debug: setDevicePermissions set to 1
04/14/18 16:28:19.281 Debug: workingDirectory set to /var/lib/homegear/
04/14/18 16:28:19.281 Debug: socketPath set to /var/run/homegear/
04/14/18 16:28:19.281 Debug: dataPath set to /var/lib/homegear/
04/14/18 16:28:19.281 Debug: familyDataPath set to /var/lib/homegear/families/
04/14/18 16:28:19.282 Debug: databaseMemoryJournal set to 0
04/14/18 16:28:19.282 Debug: databaseWALJournal set to 1
04/14/18 16:28:19.282 Debug: databaseSynchronous set to 1
04/14/18 16:28:19.282 Debug: databaseMaxBackups set to 10
04/14/18 16:28:19.282 Debug: logfilePath set to /var/log/homegear/
04/14/18 16:28:19.282 Debug: enableUPnP set to 1
04/14/18 16:28:19.282 Debug: caPath set to /etc/homegear/homegearca.crt
04/14/18 16:28:19.282 Debug: certPath set to /etc/homegear/homegear.crt
04/14/18 16:28:19.282 Debug: keyPath set to /etc/homegear/homegear.key
04/14/18 16:28:19.282 Debug: loadDHParamsFromFile set to 1
04/14/18 16:28:19.282 Debug: dhParamPath set to /etc/homegear/dh1024.pem
04/14/18 16:28:19.282 Debug: deviceDescriptionPath set to /etc/homegear/devices/
04/14/18 16:28:19.282 Debug: clientSettingsPath set to /etc/homegear/rpcclients.conf
04/14/18 16:28:19.282 Debug: serverSettingsPath set to /etc/homegear/rpcservers.conf
04/14/18 16:28:19.283 Debug: mqttSettingsPath set to /etc/homegear/mqtt.conf
04/14/18 16:28:19.283 Debug: familyConfigPath set to /etc/homegear/families/
04/14/18 16:28:19.283 Debug: phpIniPath set to /etc/homegear/php.ini
04/14/18 16:28:19.283 Debug: gpioPath set to /sys/class/gpio/
04/14/18 16:28:19.283 Debug: scriptPath set to /var/lib/homegear/scripts/
04/14/18 16:28:19.283 Debug: enableNodeBlue set to 1
04/14/18 16:28:19.283 Debug: nodeBluePath set to /var/lib/homegear/node-blue/
04/14/18 16:28:19.283 Debug: nodeBlueDataPath set to /var/lib/homegear/node-blue/data/
04/14/18 16:28:19.283 Debug: nodeBlueDebugOutput set to 1
04/14/18 16:28:19.283 Debug: libraryPath set to /var/lib/homegear/modules/
04/14/18 16:28:19.283 Debug: firmwarePath set to /usr/share/homegear/firmware/
04/14/18 16:28:19.283 Debug: tempPath set to /var/lib/homegear/tmp/
04/14/18 16:28:19.283 Debug: lockFilePath set to /var/run/homegear/
04/14/18 16:28:19.284 Debug: lockFilePathPermissions set to 504
04/14/18 16:28:19.284 Debug: lockFilePathUser set to homegear
04/14/18 16:28:19.284 Debug: lockFilePathGroup set to homegear
04/14/18 16:28:19.284 Debug: Added replaceClientServerAddress xmlrpc_bin://127.0.0.1:1999 xmlrpc_bin://$remoteip:1999
04/14/18 16:28:19.284 Debug: Added replaceClientServerAddress http://127.0.0.1:9292/bidcos http://$remoteip:9292/bidcos
04/14/18 16:28:19.284 Debug: prioritizeThreads set to 1
04/14/18 16:28:19.284 Debug: secureMemorySize set to 65536
04/14/18 16:28:19.284 Debug: workerThreadWindow set to 3000
04/14/18 16:28:19.284 Debug: scriptEngineMaxThreadsPerScript set to 4
04/14/18 16:28:19.284 Debug: scriptEngineMaxScriptsPerProcess set to 50
04/14/18 16:28:19.285 Debug: scriptEngineThreadCount set to 5
04/14/18 16:28:19.285 Debug: scriptEngineServerMaxConnections set to 10
04/14/18 16:28:19.285 Debug: scriptEngineWatchdogTimeout set to 60000
04/14/18 16:28:19.285 Debug: scriptEngineManualClientStart set to 0
04/14/18 16:28:19.285 Debug: nodeBlueProcessingThreadCountServer set to 5
04/14/18 16:28:19.285 Debug: nodeBlueProcessingThreadCountNodes set to 10
04/14/18 16:28:19.285 Debug: nodeBlueServerMaxConnections set to 50
04/14/18 16:28:19.285 Debug: maxNodeThreadsPerProcess set to 60
04/14/18 16:28:19.285 Debug: nodeBlueWatchdogTimeout set to 60000
04/14/18 16:28:19.285 Debug: nodeBlueManualClientStart set to 0
04/14/18 16:28:19.285 Debug: ipcThreadCount set to 5
04/14/18 16:28:19.285 Debug: ipsServerMaxConnections set to 20
04/14/18 16:28:19.285 Debug: cliServerMaxConnections set to 50
04/14/18 16:28:19.285 Debug: rpcServerMaxConnections set to 50
04/14/18 16:28:19.286 Debug: rpcServerThreadPriority set to 0
04/14/18 16:28:19.286 Debug: rpcServerThreadPolicy set to 0
04/14/18 16:28:19.286 Debug: rpcClientMaxThreads set to 50
04/14/18 16:28:19.286 Debug: rpcClientThreadPriority set to 0
04/14/18 16:28:19.286 Debug: rpcClientThreadPolicy set to 0
04/14/18 16:28:19.286 Debug: workerThreadPriority set to 0
04/14/18 16:28:19.286 Debug: workerThreadPolicy set to 0
04/14/18 16:28:19.286 Debug: physicalInterfaceThreadPriority set to 45
04/14/18 16:28:19.286 Debug: physicalInterfaceThreadPolicy set to 1
04/14/18 16:28:19.286 Debug: packetReceivedThreadPriority set to 0
04/14/18 16:28:19.286 Debug: packetReceivedThreadPolicy set to 0
04/14/18 16:28:19.286 Debug: eventThreadCount set to 5
04/14/18 16:28:19.287 Debug: eventThreadPriority set to 0
04/14/18 16:28:19.287 Debug: eventThreadPolicy set to 0
04/14/18 16:28:19.287 Loading RPC server settings from /etc/homegear/rpcservers.conf
04/14/18 16:28:19.287 Debug: interface of server RPCServer1 set to ::
04/14/18 16:28:19.287 Debug: port of server RPCServer1 set to 2001
04/14/18 16:28:19.287 Debug: xmlrpcServer of server RPCServer1 set to 1
04/14/18 16:28:19.287 Debug: jsonrpcServer of server RPCServer1 set to 1
04/14/18 16:28:19.288 Debug: webServer of server RPCServer1 set to 1
04/14/18 16:28:19.288 Debug: restServer of server RPCServer1 set to 1
04/14/18 16:28:19.288 Debug: contentPath of RPC server RPCServer1 set to /var/lib/homegear/www/rpc/
04/14/18 16:28:19.288 Debug: webSocket of server RPCServer1 set to 1
04/14/18 16:28:19.288 Debug: ssl of server RPCServer1 set to 0
04/14/18 16:28:19.288 Debug: authType of server RPCServer1 set to 0
04/14/18 16:28:19.288 Debug: websocketauthtype of server RPCServer1 set to 3
04/14/18 16:28:19.288 Debug: interface of server RPCServer2 set to ::
04/14/18 16:28:19.288 Debug: port of server RPCServer2 set to 2002
04/14/18 16:28:19.288 Debug: xmlrpcServer of server RPCServer2 set to 1
04/14/18 16:28:19.288 Debug: jsonrpcServer of server RPCServer2 set to 1
04/14/18 16:28:19.288 Debug: webServer of server RPCServer2 set to 1
04/14/18 16:28:19.288 Debug: restServer of server RPCServer2 set to 1
04/14/18 16:28:19.288 Debug: contentPath of RPC server RPCServer2 set to /var/lib/homegear/www/rpc/
04/14/18 16:28:19.288 Debug: webSocket of server RPCServer2 set to 1
04/14/18 16:28:19.288 Debug: ssl of server RPCServer2 set to 1
04/14/18 16:28:19.289 Debug: authType of server RPCServer2 set to 0
04/14/18 16:28:19.289 Debug: websocketauthtype of server RPCServer2 set to 3
04/14/18 16:28:19.289 Debug: diffieHellmanKeySize of server RPCServer2 set to 1024
04/14/18 16:28:19.289 Debug: interface of server RPCServer3 set to ::
04/14/18 16:28:19.289 Debug: port of server RPCServer3 set to 2003
04/14/18 16:28:19.289 Debug: xmlrpcServer of server RPCServer3 set to 1
04/14/18 16:28:19.289 Debug: jsonrpcServer of server RPCServer3 set to 1
04/14/18 16:28:19.289 Debug: webServer of server RPCServer3 set to 1
04/14/18 16:28:19.289 Debug: restServer of server RPCServer3 set to 1
04/14/18 16:28:19.289 Debug: contentPath of RPC server RPCServer3 set to /var/lib/homegear/www/rpc/
04/14/18 16:28:19.289 Debug: webSocket of server RPCServer3 set to 1
04/14/18 16:28:19.289 Debug: ssl of server RPCServer3 set to 1
04/14/18 16:28:19.289 Debug: authType of server RPCServer3 set to 1
04/14/18 16:28:19.289 Debug: websocketauthtype of server RPCServer3 set to 3
04/14/18 16:28:19.289 Debug: diffieHellmanKeySize of server RPCServer3 set to 1024
04/14/18 16:28:19.290 Loading RPC client settings from /etc/homegear/rpcclients.conf
04/14/18 16:28:19.290 Debug: hostname of RPC client ExampleClient1 set to myhostname
04/14/18 16:28:19.290 Debug: caFile of RPC client ExampleClient1 set to /path/to/ca-certficate
04/14/18 16:28:19.290 Debug: verifyCertificate of RPC client ExampleClient1 set to 1
04/14/18 16:28:19.290 Debug: forceSSL of RPC client ExampleClient1 set to 0
04/14/18 16:28:19.290 Debug: authType of RPC client ExampleClient1 set to 1
04/14/18 16:28:19.290 Debug: userName of RPC client ExampleClient1 set to myuser
04/14/18 16:28:19.291 Debug: password of RPC client ExampleClient1 was set.
04/14/18 16:28:19.291 Debug: certFile of RPC client ExampleClient1 set to /path/to/client.crt
04/14/18 16:28:19.291 Debug: keyFile of RPC client ExampleClient1 set to /path/to/client.key
04/14/18 16:28:19.291 Debug: retries of RPC client ExampleClient1 set to 3
04/14/18 16:28:19.291 Debug: timeout of RPC client ExampleClient1 set to 15000000
04/14/18 16:28:19.291 Debug: hostname of RPC client ExampleClient2 set to 192.168.178.89
04/14/18 16:28:19.291 Debug: retries of RPC client ExampleClient2 set to 5
04/14/18 16:28:19.291 Debug: timeout of RPC client ExampleClient2 set to 30000000
04/14/18 16:28:19.291 Debug (MQTT settings): enabled set to 0
04/14/18 16:28:19.292 Debug (MQTT settings): brokerHostname set to localhost
04/14/18 16:28:19.292 Debug (MQTT settings): brokerPort set to 1883
04/14/18 16:28:19.292 Debug (MQTT settings): clientName set to Homegear
04/14/18 16:28:19.292 Debug (MQTT settings): prefix set to homegear/
04/14/18 16:28:19.292 Debug (MQTT settings): homegearId set to 1234-5678-9abc
04/14/18 16:28:19.292 Debug (MQTT settings): retain set to 1
04/14/18 16:28:19.292 Debug (MQTT settings): processingThreadCount set to 5
04/14/18 16:28:19.292 Debug (MQTT settings): plainTopic set to 1
04/14/18 16:28:19.292 Debug (MQTT settings): jsonTopic set to 1
04/14/18 16:28:19.292 Debug (MQTT settings): jsonobjTopic set to 1
04/14/18 16:28:19.292 Debug (MQTT settings): enableSSL set to 
04/14/18 16:28:19.293 Starting Homegear...
04/14/18 16:28:19.293 Homegear version 0.8.0-2171
04/14/18 16:28:19.293 Git commit SHA of libhomegear-base: -
04/14/18 16:28:19.293 Git branch of libhomegear-base:     -
04/14/18 16:28:19.293 Git commit SHA of Homegear:         -
04/14/18 16:28:19.293 Git branch of Homegear:             -
04/14/18 16:28:19.294 Info: Setting allowed core file size to "4294967295" for user with id 0 and group with id 0.
04/14/18 16:28:19.294 Info: Core file size now is "4294967295".
04/14/18 16:28:19.294 Info: Setting maximum thread priority to "0" for user with id 0 and group with id 0.
04/14/18 16:28:19.294 Info: Maximum thread priority now is "0".
04/14/18 16:28:19.316 Info: Backing up database...
04/14/18 16:28:22.707 Initializing database...
04/14/18 16:28:22.709 Critical: Unknown database version: 0.7.1
04/14/18 16:28:22.709 Critical: Unknown database version: 0.7.1
04/14/18 16:28:22.711 Closing database...
04/14/18 16:28:22.711 Debug: Can't execute "COMMIT": cannot commit - no transaction is active
root@hassbian:/var/log/homegear# 

Installed packages:
root@hassbian:/var/log/homegear# dpkg -l |grep home
ii  homegear                        0.8.0-2171                   armhf        Interface program to your smart home devices
rc  homegear-gateway                0.7.15-1580                  armhf        Universal communication gateway for Homegear
ii  homegear-influxdb               0.8.0-2171                   armhf        Passes variable changes in Homegear to InfluxDB
ii  homegear-licensing              0.8.0-2171                   armhf        Default licensing module for Homegear
ii  homegear-management             0.8.0-2171                   armhf        Management service for Homegear
ii  homegear-max                    0.8.0-2171                   armhf        HomeMatic BidCoS module for Homegear
ii  homegear-nodes-core             0.8.0-2171                   armhf        Core nodes for Homegear's Node-BLUE
ii  homegear-nodes-extra            0.8.0-2171                   armhf        Extra nodes for Homegear's Node-BLUE
ii  libhomegear-base                0.8.0-2171                   armhf        Base library for Homegear
ii  libhomegear-ipc                 0.1.1-8                      armhf        IPC library for Homegear
ii  libhomegear-node                0.1.6-22                     armhf        Node library for Homegear

OS:
root@hassbian:/var/log/homegear# uname -a
Linux hassbian 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux

**Comment by hfedcba** [comment]
It's fixed thanks to @krys1976.
