### ISSUE TITLE
Website / Webservices down

### ISSUE THREAD

**Issue by haecker-felix** [Homegear/Homegear#302]
It seems that since yesterday no Homegear webservice isn't working anymore (homepage, forum, repository, docs,...).

**Comment by hfedcba** [comment]
Thanks, it's working again :+1:. Reason: The server load was too high. I shut down a few services now. We already have new highly available servers and are currently setting them up. So in a few weeks this hopefully can't happen anymore.

**Comment by haecker-felix** [comment]
Thanks!
