### ISSUE TITLE
Missing NO_SCRIPTENGINE checks

### ISSUE THREAD

**Issue by timo-schluessler** [Homegear/Homegear#304]
While compiling Homegear without php using the NO_SCRIPTENGINE define I realized some places where this check was missing.
Also in one place an additonal parameter was missing.

[no_scriptengine.txt](https://github.com/Homegear/Homegear/files/2430995/no_scriptengine.txt)

**Comment by hfedcba** [comment]
Please check, if it works now.

**Comment by timo-schluessler** [comment]
Not yet. The CliServer.cpp fix is missing. But instead of removing the whole function scriptOutput(...) it also helps to add the missing BaseLib::ScriptEngine:: prefix for PScriptInfo.

`diff --git a/src/CLI/CliServer.cpp b/src/CLI/CliServer.cpp
index e21b7f8..0211918 100644
--- a/src/CLI/CliServer.cpp
+++ b/src/CLI/CliServer.cpp
@@ -1297,7 +1297,7 @@ void CliServer::scriptFinished(BaseLib::ScriptEngine::PScriptInfo& scriptInfo, i
        }
 }
 
-void CliServer::scriptOutput(PScriptInfo& scriptInfo, std::string& output, bool error)
+void CliServer::scriptOutput(BaseLib::ScriptEngine::PScriptInfo& scriptInfo, std::string& output, bool error)
 {
        try
        {
@@ -1326,4 +1326,4 @@ void CliServer::scriptOutput(PScriptInfo& scriptInfo, std::string& output, bool
        }
 }
 
-}
\ No newline at end of file
+}`
