### ISSUE TITLE
Unable to retreive Values parameterset with rest api

### ISSUE THREAD

**Issue by Cycor** [Homegear/Homegear#308]
Following the documentation I'm trying to retreive the values of a device, but I always get the MASTER parameterset back.
 
Call: api/v1/config/1/1/VALUES

Looking at the RestServer.cpp source you are not using the typeOrVariable variable at all and using "parts.at(5)" for the third parameter of getParamset, but typeOrVariable is at position 6.

**Comment by hfedcba** [comment]
True and in parts.at(5) is the channel... Thanks.

**Comment by hfedcba** [comment]
It's fixed in the next nightly.
