### ISSUE TITLE
New release is missing

### ISSUE THREAD

**Issue by avanc** [Homegear/Homegear#312]
The latest release (0.7.30) is already very old and suffers form important features like the admin-ui.
When is a new release planned?

**Comment by hfedcba** [comment]
Actually due to a changed work flow we are just not creating the "Release" tags anymore. The current stable release is always in the master branch. But I now created a 0.7.39 release ;-).

**Comment by avanc** [comment]
Thanks, that was quick!

You are not planning releases anymore? Is your proposal to use git (e.g. homgear-git vs homegear)?
https://aur.archlinux.org/packages/?O=0&K=homegear

Dependency handling gets complicated, as one has to update nut just homegear but also e.g. homegear-homematicbidcos.

**Comment by hfedcba** [comment]
Ah ok, then I will see, that we automatically create releases again.

**Comment by avanc** [comment]
Sounds good.

Maybe worth a look:
* https://github.com/dominique-mueller/automatic-release
    * nodejs based
    * Can be integrated into Travis CI
* https://github.com/github-tools/github-release-notes
    * Looks very powerfull
    * nodejs
* https://developer.github.com/v3/repos/releases/#create-a-release
   * The official Github API

**Comment by hfedcba** [comment]
We are using the GitHub-API. GitHub is not the problem though, the problem are other platforms we are also using (i. e. for internal code, external projects, ...). Actually "problem" is the wrong word - it's only laziness... So I will make sure, releases are created again from now on.
