### ISSUE TITLE
Compiler error concerning zlib and possible solution

### ISSUE THREAD

**Issue by ahuemmer** [Homegear/Homegear#316]
Every now and then I am compiling Homegear from source (as described [here](https://doc.homegear.eu/homegear/installation.html#compiling-from-source)) on a Gentoo system. Recently, when compiling Homegear itself, I got this error:

```libhomegear-base.so undefined reference to `deflateInit2_'```
(and about five more, all referring zlib functionality)

I found out, that the problem can be solved on my system by adding

```LIBS += -lz```

to `src/Makefile.am` of libhomegear-base (and, of course, recompiling libhomegear-base).

I don't have enough knowledge about the whole system to be able to tell whether this is the right solution in general (or, at least, has to be surrounded with an `if` statement...), but it might be the right approach... 😃

**Comment by hfedcba** [comment]
Adding "-lz" is not a problem. I added it to my local copy and it will be commited to the dev-Branch of libhomegear-base on GitHub soon. Thanks for reporting the issue!
