### ISSUE TITLE
Homematic-Max sets temperature to 5.0

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [Homegear/Homegear#319]
When I set the temperature to 4.5 via mqtt, homegear instead sets the temperature to 5.0.

**Comment by ibcsim** [comment]
try setting a different Temperature. Probably 5 is the min value and 5.5 would work fine.?

**Comment by Unkn0wn-MDCLXIV** [comment]
That obviously works fine, but setting the temp to 4.5 will turn the thermostat off.
It used to work flawlessly, some updates might have broken it.

**Comment by mape2k** [comment]
I can confirm this issue. After one of the last updates you cannot set 4.5 for "off".

Documentation also says 5 as minimal value:
https://ref.homegear.eu/device.html?directory=MAX%21&file=BC-RT-TRX-CyG-2.xml&familyLink=max&name=BC-RT-TRX-CyG-2#affixSubsubsection1_0_17

Some month ago, setting 4.5 for "off" works flawlessly.

**Comment by mape2k** [comment]
Checking dpkg-log ... 
* 0.7.38 - must be ok
* 0.7.39 - maybe working, cannot confirm nor refuse
* 0.7.40 - problem exists

**Comment by hfedcba** [comment]
The issue is already fixed. in the current nightly. The next stable will also contain the fix.
