### ISSUE TITLE
LOWBAT for HM-WDS40-TH-I-2

### ISSUE THREAD

**Issue by janecker** [Homegear/Homegear#322]
Hi,

I have two homematic thermostats of the type HM-WDS40-TH-I-2 which are battery powered. It seems like homegear is only reporting temperature and humidity but no lowbat indication.

Regarding to the FHEM wiki ([https://wiki.fhem.de/wiki/HM-WDS40-TH-I_Funk-Temperatur-/Feuchtesensor_innen_(IT)]) it seems like it has a lowbat indication. Are there any limitations that prevent using the battery indication or is it just missing in the device description?

**Comment by hfedcba** [comment]
So the service message `LOWBAT` and the variable `LOWBAT` on channel 0 stay unset?

**Comment by janecker** [comment]
If I remember correctly there was no low bat variable. I checked the data send via Mqtt and it only contained humidity and temperature. May have to check again as some time passed since than :).

**Comment by hfedcba** [comment]
That's the variable that is set, when the battery is low. All other variables are secondary - if they exist.

**Comment by janecker** [comment]
Ok I just got around checking that again. This is what the mqtt message payload looks like from these thermostats:
![image](https://user-images.githubusercontent.com/1313022/71199558-7c0eb980-2296-11ea-812e-5e27691744b2.png)
As you can see there is now lowbat value transmitted. Is there something in my configuration wrong?

**Comment by hfedcba** [comment]
`LOWBAT` is only rarely updated. Please do:

`homegear -e rc 'print_v($hg->getValue(<Peer ID>, 0, "LOWBAT");'`

**Comment by janecker** [comment]
Seems like the parameter is available:

`root@4942def18894:/# homegear -e rc 'print_v($hg->getValue(32, 0, "LOWBAT"));'
(Boolean) 0`

But why is it not present in the MQTT messages? As far as I could tell from the other device types the lowbat parameters are always present (even though they do not always report as true in case of low bat). Maybe I have to grab one of my thermostats and play around with the voltage a bit to check if I actually receive the low battery warnings.

**Comment by hfedcba** [comment]
> But why is it not present in the MQTT messages?

Probably because it was never sent and therefore is not cached. It's only updated, when the state is changed.

I'm closing this issue now. If the parameter is not working, I'm going to reopen it, but it should work.
