### ISSUE TITLE
Build --without-scriptengine not supported?

### ISSUE THREAD

**Issue by matgnt** [Homegear/Homegear#324]
Hi all,

is there reason why --without-scriptengine is not supported?
https://github.com/Homegear/Homegear/blob/master/configure.ac#L80

I'm trying to build a minimalist version of homegear and I'm on a good way to get a build without the scriptengine. Now I'm asking myself _why_ it got disabled. Would homegear still work without the scriptengine or is this useless effort I'm doing here?

My reason behind is:
I want to use "HomeMatic BidCoS module" with homegear and python3-homegear (or maybe another event handler later) through an IPC connection. I'm trying to remove as many dependencies as possible :)

Any thoughts?
Thanks for your help!

**Comment by hfedcba** [comment]
It should work again now. Actually I have no idea, why it got disabled.
