### ISSUE TITLE
Please do not reboot without asking

### ISSUE THREAD

**Issue by 3cst4sy** [Homegear/Homegear#331]
As title says, please add confirmation dialog before reboot whole system. (at CA build site)

**Comment by hfedcba** [comment]
It's actually an Admin UI issue, but I will pass it along.

**Comment by 3cst4sy** [comment]
Thanks.

**Comment by m-scheffler** [comment]
Is fixed within the next nightly, but the homegear-process has to be restarted to make use of the new CA. This is still done automatically.
