### ISSUE TITLE
Homegear does not find fontawesome.min.css

### ISSUE THREAD

**Issue by pinae** [Homegear/Homegear#344]
I use homegear with the docker container. This installation does not find `fontawesome.min.css`. However there is a file named `fontawesome-all.min.css`.

I can fix the problem with this symlink (in the data folder of the container):
```bash
cd lib/admin-ui/public/css/ && ln -s fontawesome-all.min.css fontawesome.min.css
```

This filename mismatch should be pretty easy to fix...

**Comment by hfedcba** [comment]
Hi @pinae,

thanks!

The error already is fixed. When you tested, it was already fixed in the nightly version. In the meantime the stable version was updated as well.

Cheers,

Sathya
