### ISSUE TITLE
Menu is missing (at least in the docker image)

### ISSUE THREAD

**Issue by pinae** [Homegear/Homegear#345]
There used to be a menu on the left side of the screen. After my last update of the Homegear Docker container it is gone. It now looks like this:
![screenshot_missing_menu](https://user-images.githubusercontent.com/1160927/88913490-551f5980-d261-11ea-86e6-4315853490e6.jpg)

**Comment by hfedcba** [comment]
Hi @pinae,

thanks again ;-)!

The error already is fixed. When you tested, it was already fixed in the nightly version. In the meantime the stable version was updated as well.

Cheers,

Sathya
