### ISSUE TITLE
Gateway IP Address not shown in admin ui

### ISSUE THREAD

**Issue by slaecker** [Homegear/Homegear#346]
The admin ui doesn't show the IP after adding a new gateway, the sqlite db contains the IP as entered. I'm running Homegear in Docker (completely fresh, no old data), tried the stable and testing tags.

![homegear_gws](https://user-images.githubusercontent.com/8582375/88931714-b7318c00-d26c-11ea-9e40-efc76e4f7d47.png)

![homegear_db](https://user-images.githubusercontent.com/8582375/88932572-c8c76380-d26d-11ea-9c8c-5cdc5f96d289.png)

**Comment by hfedcba** [comment]
Thanks. It's fixed in the next nightly.
