### ISSUE TITLE
Installing Homegear on Raspberry 4 with Raspbian returns an error

### ISSUE THREAD

**Issue by RudyReindeer** [Homegear/Homegear#359]
I am trying to install homegear new on a new raspberry 4, as described under "https://homegear.eu/downloads.html?version=0.7&system=raspbian_bullseye":
After  “apt update”, I get the following error message:
	“Das Laden der konfigurierten Datei »main/binary-arm64/Packages« wird übersprungen, da das Depot »https://apt.homegear.eu/raspberry_pi_os/bullseye/homegear/stable bullseye InRelease« die Architektur »arm64« nicht unterstützt.“
lsb_release -a:
     Distributor ID: Debian
     Description:    Debian GNU/Linux 11 (bullseye)
     Release:        11
     Codename:       bullseye
lscpu:		
    CPU op-mode(s):                  32-bit, 64-bit
   Vendor ID:                       ARM
Thank you for any advice Rudy

**Comment by RudyReindeer** [comment]
The install script on the same page ("https://homegear.eu/downloads.html?version=0.7&system=raspbian_bullseye":) works just fine. 
There is likely a typo in the repository, that you may want to fix. Put this is not a REAL issue.

**Comment by hfedcba** [comment]
Actually I assume, you installed the 64 bit version of Rapsberry Pi OS. The only question is, why it worked using the install script - it does nothing different and also uses APT.

**Comment by hfedcba** [comment]
I'm reopening the issue until we have a 64 bit Raspberry Pi OS repo. We are actually waiting for the 64 bit version for a long time...

**Comment by hfedcba** [comment]
I just saw, that 64 bit Raspberry Pi OS is a regular Debian. Could you check and post the content of your `/etc/apt/sources.list.d/homegear.list`? I assume, the installer chose Debian and that is why it worked.

**Comment by RudyReindeer** [comment]
Hello hfedcba, 
the present `/etc/apt/sources.list.d/homegear.list` states:
‘deb https://apt.homegear.eu/debian/bullseye/homegear/stable/ bullseye main’, so a regular Debian.
 Does this help? I am happy to check whatever is helpful, if you let me know.

**Comment by hfedcba** [comment]
ok, perfect. It's exactly as described above - the installer detected Debian and chose the correct repository. We updated the Homegear webpage and added instructions for arm64 Raspberry Pi OS.

**Comment by hfedcba** [comment]
Thanks for your help and for posting the issue!
