### ISSUE TITLE
Raspberry Pi OS Image - disk partitioning defaults broken

### ISSUE THREAD

**Issue by bitte-ein-bit** [Homegear/Homegear#360]
# reproduceable steps
1. I downloaded the image from https://homegear.eu/downloads.html?version=0.7&system=raspbian_bullseye
2. Burned to the SD card
3. booted and SSHed to the machine
4. followed with the defaults of 2G for both partitions
5. rebooted
6. kernel panic

The problem is the disk is already 4+GB. So anything below that size will just corrupt the filesystem. On the 4th try I investigated the layout first and tried with 5GB which worked.

**Comment by hfedcba** [comment]
Thanks - it's fixed in the current image.
