### ISSUE TITLE
Homegear-Max: Log message seems incomplete

### ISSUE THREAD

**Issue by Flole998** [Homegear/Homegear#365]
Something seems to be wrong with https://github.com/Homegear/Homegear-MAX/blob/5d483c54c5e47dcb43436bca00dd052acaccde21/src/PhysicalInterfaces/HomegearGateway.cpp#L205

The only debug output I get is
```
12/29/22 02:57:29.177 Module MAX: MAX! Homegear Gateway "My-Max-Gateway": Info: Sending:
```

while on the similar code for Bidcos (see https://github.com/Homegear/Homegear-HomeMaticBidCoS/blob/2c5b609f304b07bcf37400ad03d1646d7c0efabd/src/PhysicalInterfaces/HomegearGateway.cpp#L292)  the string is properly appended.

```
12/29/22 03:41:58.962 Module HomeMatic BidCoS: HomeMatic Homegear Gateway "My-Homematic-Gateway": Info: Sending: 0AXXXXXXXXXXXXXX
```

@hfedcba Any idea what might be going on here?

**Comment by hfedcba** [comment]
Thanks, it's fixed. The wrong array element was referenced.
