### ISSUE TITLE
Aufruf von listDevices() triggert Absturz/Neustart

### ISSUE THREAD

**Issue by jboeddeker** [Homegear/Homegear#367]
Mit folgendem Kommando kann ich Homegear reproduzierbar zum Absturz bringen:

homegear -e rc 'print_r($hg->listDevices())'

**Comment by jboeddeker** [comment]
Das führt dazu, das Homegear nicht mehr mit openHAB zusammenarbeitet.

**Comment by hfedcba** [comment]
Hi @jboeddeker,

danke für das Analysieren und vor allem für den Backtrace. Ich kann bei mir das Problem nicht reproduzieren, daher war letzterer sehr Hilfreich. Ich bin die letzten Codeänderungen durchgegangen und gehe davon aus, dass das Problem jetzt behoben ist. Ich kann es jedoch leider nicht testen. Wenn du das nächste Nightly testen würdest, wäre ich dir daher sehr dankbar. Wenn du mir dein System nennst, kann ich das Kompilieren eines Nightlies schnell forcieren (sonst dauert es bis zu zwei Tage).

Viele Grüße

Sathya

**Comment by jboeddeker** [comment]
Hi. 

Läuft. Kein Absturz mehr und openHAB enpfängt wieder Werte!

Vielen Dank!

**Comment by hfedcba** [comment]
Hi Joachim,

puh. Noch einmal vielen Dank dir für's Melden!

Viele Grüße

Sathya

**Comment by jboeddeker** [comment]
Hallo Sathya,

so ganz ist das doch noch nicht wieder in Ordnung. Ich habe ein massives
Problem in openHAB mit "Channel not found for datapoint". Das Problem gibt
es schon ewig, betraf aber immer nur ein paar (zufällige) Geräte .

Das Problem tritt auf, wenn ein Wert für eine Gerätevariable nach openHAB
gemeldet wird, für den im openHAB-Modell kein Kanal gefunden wird.

Jetzt ist es immens und betrifft fast jedes Gerät. Kann es sein, dass durch
irgendeinen Fehler nicht alle Channels mit den richtigen Namen bei
listDevices gefunden werden? Das openHAB-Modell wird meines Wissens über
das Ergebnis von listDevices aufgebaut.

Vielen Dank und viele Grüße

Joachim

Am Di., 31. Jan. 2023 um 23:15 Uhr schrieb Sathya Laufer <
***@***.***>:

**Comment by hfedcba** [comment]
Hallo @jboeddeker,

sorry, erst jetzt gesehen - irgendwie habe ich keine E-Mail-Benachrichtigung bekommen...

Hmm, hättest du ein Beispielgerät mit Variable, bei der das passiert für mich? Dann schaue ich mir das an und fixe das.

Viele Grüße

Sathya

**Comment by jboeddeker** [comment]
Hi @hfedcba,

nicht schlimm. Das Problem ist auf openHAB-Seite gelöst. Mit dem Upgrade auf openHAB 3.4 wurde das Problem irrelevant, da die fehlenden Channels dann in openHAB nachgebaut werden, sobald Daten auftauchen. (Vorher wurden Channels nur bei der Einrichtung aufgebaut und die Daten wurden dann verworfen.)

Das war ein uraltes Problem bei openHAB, hatte irgendwas mit dem Timing und der Menge der Geräte/Variablen zu tun. Das Problem trat vermehrt bei Geräten mit vielen Variablen auf, z.B. den Wandthermostaten.

Viele Grüße

Joachim
